### ISSUE TITLE
可不可以加入\includepdf的宏包

### ISSUE THREAD

**Issue by Nicooo-Wang** [note286/xdupgthesis#10]
辛苦同学啦

**Comment by note286** [comment]
@Nicooo-Wang 如果你是为了插入一个多页pdf的某一页的话，`\includegraphics[page=2]{fig}`即可，不需要使用`pdfpages`宏包的`\includepdf`命令，如果是这个需求，我在README增加下这个的使用方法。

**Comment by Nicooo-Wang** [comment]
> @Nicooo-Wang 如果你是为了插入一个多页pdf的某一页的话，`\includegraphics[page=2]{fig}`即可，不需要使用`pdfpages`宏包的`\includepdf`命令，如果是这个需求，我在README增加下这个的使用方法。

好的好的，只需要插入某页，谢谢啦

**Comment by note286** [comment]
@Nicooo-Wang 你是Microsoft Visio画图吗？可以只打印或者导出某一页的。好奇你是什么使用场景。

**Comment by Nicooo-Wang** [comment]
visio绘图，但是为了便于管理，安装章节创建的visio文件，图片排序后自适应图像处理，批量导出多页pdf，如果单打的话管理会很混乱，这样我只需要控制visio页面的顺序，输出pdf-page就可以实现插图管理了，刚才测试了一下\includegraphics确实可以插入单页，谢谢啦。

**Comment by Nicooo-Wang** [comment]
真的很感谢楼主，这两天看issue，大家好像都没太用过latex，今天还看到个issue自己不会调整图像大小的🤣🤣🤣楼主真的是好人哇

**Comment by note286** [comment]
> visio绘图，但是为了便于管理，安装章节创建的visio文件，图片排序后自适应图像处理，批量导出多页pdf，如果单打的话管理会很混乱，这样我只需要控制visio页面的顺序，输出pdf-page就可以实现插图管理了，刚才测试了一下\includegraphics确实可以插入单页，谢谢啦。

如果你说的`自适应图像处理`指的是Microsoft Visio-设计-自动调整大小，那么不建议使用该功能，该功能会导致一旦有页复制或者页重命名操作，整个文件内所有页均会自动触发自动调整大小动作，哪怕是新建的页也会如此，在开启视图-显示-任务窗格-大小和位置功能的情况下，会导致坐标变化，形成非整数坐标，不利于后续修改或继续作图。个人建议最省事也最方便的方法是不使用自动调整大小功能，直接打印，不要选择导出，导出会导致所有文本向右下角偏移0.25磅左右，当文本与线框距离较近时，视觉效果尤为明显。最后使用README提及的`pdfcrop`命令对pdf文件进行裁剪，支持一个命令裁剪多页pdf。

**Comment by note286** [comment]
> 真的很感谢楼主，这两天看issue，大家好像都没太用过latex，今天还看到个issue自己不会调整图像大小的🤣🤣🤣楼主真的是好人哇

大概是会用的用户不会提问吧，提问的肯定是不会的，那个人的问题我会在README里补充一节介绍浮动体的概念。

**Comment by DizzyKnight233** [comment]
> 真的很感谢楼主，这两天看issue，大家好像都没太用过latex，今天还看到个issue自己不会调整图像大小的🤣🤣🤣楼主真的是好人哇

是说我吗🤣，虽然确实不咋会用，但是感觉是浮动不是大小的问题啊，我用一样的两张图，一张6cm高一张12cm高也是占一页，两张都6cm高也是占一页
```
\begin{figure}
    \centering
    \includegraphics[width=.6\linewidth,height=14cm]{S2/Fig15}
    \caption{xxx}
    \label{fig2.10}
\end{figure}
\begin{figure}
    \centering
    \includegraphics[width=.6\linewidth,height=6cm]{S2/Fig16}
    \caption{xxx}
    \label{fig2.11}
\end{figure}
```
这样写没错吧，而且前一页最后一行和后一页第一行是同一段文字

**Comment by note286** [comment]
同时指定高度和宽度会拉伸图片吧，如果你非要同时指定，可以添加`keepaspectratio`参数，一般建议仅指定宽度即可。不过正常来讲，图片字号略小于正文字号，因此，不应该对图片有任何的缩放，在绘图时就需要考虑到图片的尺寸，在规定的尺寸内使用合适的字号绘图，所以我才在README中标注了本模板的页面宽度和高度以供参考。

关于你说的图片占用一页的问题，LaTeX引擎有自己的算法和评估每个页面，如果想要修改，你可以参考[floats - avoid that figure gets its own page - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/68516/avoid-that-figure-gets-its-own-page)，我考虑下是否直接在模板中修改该数值。

**Comment by Nicooo-Wang** [comment]
> > visio绘图，但是为了便于管理，安装章节创建的visio文件，图片排序后自适应图像处理，批量导出多页pdf，如果单打的话管理会很混乱，这样我只需要控制visio页面的顺序，输出pdf-page就可以实现插图管理了，刚才测试了一下\includegraphics确实可以插入单页，谢谢啦。
> 
> 如果你说的`自适应图像处理`指的是Microsoft Visio-设计-自动调整大小，那么不建议使用该功能，该功能会导致一旦有页复制或者页重命名操作，整个文件内所有页均会自动触发自动调整大小动作，哪怕是新建的页也会如此，在开启视图-显示-任务窗格-大小和位置功能的情况下，会导致坐标变化，形成非整数坐标，不利于后续修改或继续作图。个人建议最省事也最方便的方法是不使用自动调整大小功能，直接打印，不要选择导出，导出会导致所有文本向右下角偏移0.25磅左右，当文本与线框距离较近时，视觉效果尤为明显。最后使用README提及的`pdfcrop`命令对pdf文件进行裁剪，支持一个命令裁剪多页pdf。

学到了，谢谢！

**Comment by DizzyKnight233** [comment]
> 同时指定高度和宽度会拉伸图片吧，如果你非要同时指定，可以添加`keepaspectratio`参数，一般建议仅指定宽度即可。不过正常来讲，图片字号略小于正文字号，因此，不应该对图片有任何的缩放，在绘图时就需要考虑到图片的尺寸，在规定的尺寸内使用合适的字号绘图，所以我才在README中标注了本模板的页面宽度和高度以供参考。
> 
> 关于你说的图片占用一页的问题，LaTeX引擎有自己的算法和评估每个页面，如果想要修改，你可以参考[floats - avoid that figure gets its own page - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/68516/avoid-that-figure-gets-its-own-page)，我考虑下是否直接在模板中修改该数值。

是的我写上去的都是只指定了宽度保持横纵比，定高度只是为了试一试。图都是之前发论文针对双排画的，按导师要求转了eps，原visio文件丢了也懒得重画了。

看了这个懂了，意思浮动体并不需要占满整页，只需要超过一定比例就独享整页了，已经修改参数解决了🤣非常感谢楼主，我那个issue可以关了

**Comment by note286** [comment]
@DizzyKnight233 你和 @Nicooo-Wang 是认识吗？咋直接就跑到隔壁issue里了。

**Comment by DizzyKnight233** [comment]
> @DizzyKnight233 你和 @Nicooo-Wang 是认识吗？咋直接就跑到隔壁issue里了。

没不认识，想看看其他issue都啥问题，看到他提到不会调大小的感觉是在说我就插了两句

**Comment by note286** [comment]
@DizzyKnight233 我说嘛，我一开始都没注意到是两个人，后来才发现不对劲。
