### ISSUE TITLE
appendixes ,texstudio提示未识别的环境

### ISSUE THREAD

**Issue by dongxuqian** [note286/xdupgthesis#11]

**Comment by note286** [comment]
@dongxuqian 这是自定义的环境，不是LaTeX原生环境，请问是否可以正常编译。

**Comment by dongxuqian** [comment]
@note286 编译是没有问题的，模板里参考文献是在附录后，但是好像格式应该是参考文献在附录前？

**Comment by note286** [comment]
@dongxuqian 请阅读README中关于[附录](https://github.com/note286/xdupgthesis#%E9%99%84%E5%BD%95)的说明，我已补充附录放置位置的要求。
