### ISSUE TITLE
如何解决latex中section换页导致上一页内容没有填充满的问题

### ISSUE THREAD

**Issue by auroua** [note286/xdupgthesis#12]
麻烦问一下大佬，由于latex里的小节会导致换页，上一页内容还没填满，遇到小节就换页了，导致上一页的内容有很大的空白，这种问题怎么解决啊？

**Comment by note286** [comment]
@auroua 请给出测试用例，你可以随便填充一些数据，出现你说的效果即可，方便我测试。

**Comment by auroua** [comment]
麻烦你看一下如图所示的效果：

![微信截图_20211129232746](https://user-images.githubusercontent.com/2869412/144000601-eafe1670-6462-44ed-914d-df3b74f8da54.png)


![微信截图_20211129232816](https://user-images.githubusercontent.com/2869412/144000621-e7abf0bc-14d3-4004-a8b1-831cafbeea2c.png)

@note286 大佬，你邮箱能发一下么？我给你发latex的用例

**Comment by note286** [comment]
@auroua 你睿思直接私信我。

**Comment by note286** [comment]
@auroua 你查看下是否是[浮动体位置](https://github.com/note286/xdupgthesis#%E6%B5%AE%E5%8A%A8%E4%BD%93%E4%BD%8D%E7%BD%AE)所述的问题。

**Comment by note286** [comment]
@auroua 如果确实是[浮动体位置](https://github.com/note286/xdupgthesis#%E6%B5%AE%E5%8A%A8%E4%BD%93%E4%BD%8D%E7%BD%AE)所述的问题，且已经解决，稍后我会关闭该issue。

**Comment by auroua** [comment]
谢谢，谢谢，我的问题就是你说的这几个解决办法。

**Comment by note286** [comment]
> 谢谢，谢谢，我的问题就是你说的这几个解决办法。

好的，下次记得多看看文档。
