### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by ddxylq** [note286/xdupgthesis#13]
参考文献中，当会议论文缺少出版商/地信息时，参考文献中会出现[S.l.: s.n.]。具体原因是7714的定义：
FUNCTION {bbl.sine.loco}
{ entry.lang lang.zh =
    { "[出版地不详]" }
    { "[S.l.]" }
  if$
}

FUNCTION {bbl.sine.nomine}
{ entry.lang lang.zh =
    { "[出版者不详]" }
    { "[s.n.]" }
  if$
}

FUNCTION {bbl.sine.loco.sine.nomine}
{ entry.lang lang.zh =
    { "[出版地不详: 出版者不详]" }
    { "[S.l.: s.n.]" }
  if$
}

**Comment by note286** [comment]
请问你bib中缺少什么字段导致的，我没有复现成功，`inproceedings`类型中仅保留`author`和`title`字段也依然没有出现你说的情况。或者你在代码块中给出你的bib条目。

**Comment by ddxylq** [comment]
比如这个参考文献：
@INPROCEEDINGS{8292221,
author={{Lucciardi}, Jean-Alain and {Thomas}, Nathalie and {Boucheret},
Marie-Laure and Poulliat, Charly and Mesnager, Gilles},
booktitle={IEEE 28th Annual International Symposium on Personal, Indoor,
and Mobile Radio Communications (PIMRC)},
title={Receiver for FTN signaling in non-linear channel: Joint channel
estimation and synchronization},
year={2017},  volume={},  number={},  pages={1-7}}

[image: image.png]

Chloe ***@***.***> 于2021年12月6日周一 16:24写道：

**Comment by ddxylq** [comment]
对了 我用的是texlive2021+texstudio

Qiang Li ***@***.***> 于2021年12月6日周一 16:47写道：

**Comment by note286** [comment]
根据你的bib条目

```
@INPROCEEDINGS{8292221,
author={{Lucciardi}, Jean-Alain and {Thomas}, Nathalie and {Boucheret},
Marie-Laure and Poulliat, Charly and Mesnager, Gilles},
booktitle={IEEE 28th Annual International Symposium on Personal, Indoor,
and Mobile Radio Communications (PIMRC)},
title={Receiver for FTN signaling in non-linear channel: Joint channel
estimation and synchronization},
year={2017},  volume={},  number={},  pages={1-7}}
```

生成的参考文献

> Lucciardi J A, Thomas N, Boucheret M L, et al. Receiver for ftn signaling in non-linear channel: Joint channel estimation and synchronization[C]//IEEE 28th Annual International Symposium on Personal, Indoor, and Mobile Radio Communications (PIMRC). 2017: 1-7.

没有发现任何问题，我是Windows 10 + TeX Live 2021，你使用命令`latexmk`编译一下试试。

此外，不要对作者使用分组，参考文献就是规定要作者全部大写，不要强制修改。

**Comment by ddxylq** [comment]
我按照你的建议试了一下 还是不行....奇怪 我们的环境应该是一样的啊 谢谢哈

Chloe ***@***.***> 于2021年12月6日周一 17:05写道：

**Comment by ddxylq** [comment]
我是从texlive2020升级到2021之后编译的 2020被我卸载了  我也不清楚是什么bug😞

Qiang Li ***@***.***> 于2021年12月6日周一 17:12写道：

**Comment by note286** [comment]
你使用他人的LaTeX环境测试一下，如果他人的没问题，最省事的办法就是卸载干净再重装，如何卸载安装在README里读一下，如果他人的LaTeX环境下依然有问题你再找我，如果没问题也说一下，我关闭issue。

**Comment by ddxylq** [comment]
向您请教个问题可以吗？我的图表索引是这样的吗，大致是什么原因呢？
[image: image.png]
[image: image.png]

Qiang Li ***@***.***> 于2021年12月6日周一 17:13写道：

**Comment by note286** [comment]
你不要用邮件回复，你的图片根本无法显示，用浏览器进issue页面回复。

**Comment by ddxylq** [comment]
好的 谢谢

Chloe ***@***.***> 于2021年12月6日周一 17:17写道：

**Comment by note286** [comment]
如果有其他问题，请单独开issue，一个问题一个issue，方便用户后续查看。

**Comment by ddxylq** [comment]
嗯嗯 谢谢

Chloe ***@***.***> 于2021年12月6日周一 17:25写道：

**Comment by ddxylq** [comment]
还是有问题，我在您的模板基础上，只是把您bib文件里的那个会议改成了这样：
@inproceedings{TsaiCLQLB13,
author = {Wei{-}Tek Tsai and Charles J. Colbourn and Jie Luo and Guanqiu Qi and Qingyang Li and Xiaoying Bai},
title = {Test algebra for combinatorial testing},
booktitle = {{AST}},
pages = {19--25},
year = {2013}
}
然后，编译出来的就是这样了
![image](https://user-images.githubusercontent.com/58464727/144955448-bd20e136-fbe4-4934-92f1-d42a763ef42f.png)
我怀疑是不是我的设置出了问题，我更改的设置是这样的:
![image](https://user-images.githubusercontent.com/58464727/144955570-b0e12569-d832-4103-89f4-72513eec0fc7.png)
![image](https://user-images.githubusercontent.com/58464727/144955593-5d02ee9e-c82c-4cdc-8f5a-8fe9dd29e820.png)
![image](https://user-images.githubusercontent.com/58464727/144955611-8b557442-a7d3-4355-958c-3ca05c989175.png)
然后是点击这里的latexmk进行的编译：
![image](https://user-images.githubusercontent.com/58464727/144955710-6e5211c7-6f5e-452b-b0ec-dad1b9584ec6.png)

**Comment by note286** [comment]
> TSAI W, COLBOURN C J, LUO J, et al. Test algebra for combinatorial testing[C]//AST. 2013: 19-25.

我这边是这样的，用的你的bib条目

```
@inproceedings{TsaiCLQLB13,
author = {Wei{-}Tek Tsai and Charles J. Colbourn and Jie Luo and Guanqiu Qi and Qingyang Li and Xiaoying Bai},
title = {Test algebra for combinatorial testing},
booktitle = {{AST}},
pages = {19--25},
year = {2013}
}
```

这样，你在论文模板根目录下打开cmd，执行

```shell
latexmk -C
latexmk
```

这两个命令，会删除辅助文件，得到新的PDF文件，你再看下是否有问题。

**Comment by ddxylq** [comment]
我按照您的建议试了，还是那个样子，而且我用我朋友电脑（他之前没有安装过）重新安装了texlive2021和texstudio，他也是这样的情况

**Comment by note286** [comment]
我让我同学测试了，他也是新装的TeX Live 2021，新下载的模板，仅替换了你的bib条目，使用命令行编译，没有任何问题。你下载一个空模板，仅替换这一条bib文件，测试一下，使用命令编译，不要用IDE里的按钮了。还是不行，你注册个Overleaf，使用在线的测试一下，如何使用在README里写。测试完毕给我说下结果。

**Comment by ddxylq** [comment]
好的 谢谢

**Comment by note286** [comment]
一定能给你解决，拿出做实验的精神，一点一点测试，找出问题。

**Comment by ddxylq** [comment]
嗯嗯 谢谢 我突然发现一个问题哈  我之前没有配置镜像源、更新包管理器和所有包，我先试试这个，实在抱歉

**Comment by ddxylq** [comment]
已经解决了 就是因为我没有配置镜像源、更新包管理器和所有包，耽误您时间了哈，非常感谢

**Comment by note286** [comment]
> 已经解决了 就是因为我没有配置镜像源、更新包管理器和所有包，耽误您时间了哈，非常感谢

好吧，看来我要配置一下issue模板，提醒一下使用最新版更新包再提issue了。

**Comment by yxzheng24** [comment]
你好！请问一下我用你的模板编译完成后，英文参考文献中作者名字的所有字母全都是大写，这种情况正常吗？好像和之前师兄师姐的论文的英文参考文献格式（仅首字母大写）不太一样，应该怎么解决呢？谢谢~

**Comment by ddxylq** [comment]
这个可以在bib文件中对作者项再加一次{}，强制其格式为本来的类型，但是作者说要求大写，我看我师兄师姐的论文也没有全大写，这个不太确定。

yxzheng ***@***.***> 于2021年12月10日周五 12:30写道：

**Comment by note286** [comment]
@ddxylq @yxzheng24 请阅读[参考文献条目样式](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%9D%A1%E7%9B%AE%E6%A0%B7%E5%BC%8F)，可以自己下载国家标准《信息与文献 参考文献着录规则》（标准号GB/T 7714-2015）看一下示例。对于格式问题，不要轻易相信你们的师兄师姐，大部分都是稀里糊涂的。
@ddxylq 据我的经验，一般需要在bib里使用分组常见于公司或者组织名称等，至少人名不在此列。国标规定姓名就是要全部大写，虽然不好看，但这是规定啊，我也木有办法。
