### ISSUE TITLE
参考文献引用问题

### ISSUE THREAD

**Issue by KORIYN** [note286/xdupgthesis#16]
我使用您的模板。
当引用参考文献的时候，我\cite{lampert2009learning,lampert2013attribute}，pdf打印出来右上角是[5;13]，但我想要的是[5,13]。如何把分号改为逗号呢？我使用的winedt编辑器。

**Comment by note286** [comment]
你使用的是TeX Live多少的版本？2021？

**Comment by KORIYN** [comment]
对，按照您给的步骤装的

**Comment by note286** [comment]
已修复，更新`.cls`文件即可。

**Comment by KORIYN** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月30日 20:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [note286/xdupgthesis] 参考文献引用问题 (Issue #16) |

已修复，更新.cls文件即可。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
