### ISSUE TITLE
列表的行间距问题

### ISSUE THREAD

**Issue by Ticsmyc** [note286/xdupgthesis#18]
使用enumerate和itemize时，排版出来间距会特别大（不确定是不是因为我的用法不正确）

通过在cls中添加下面这几个配置，把间距缩小了，但是不太确定这样对不对，麻烦帮忙看一下~

%列表间距
\usepackage{enumitem}
\setenumerate[1]{itemsep=0pt,partopsep=0pt,parsep=\parskip,topsep=5pt}
\setitemize[1]{itemsep=0pt,partopsep=0pt,parsep=\parskip,topsep=5pt}
\setdescription{itemsep=0pt,partopsep=0pt,parsep=\parskip,topsep=5pt}

**Comment by note286** [comment]
已修改，更新`.cls`文件即可。
