### ISSUE TITLE
个人信息的中\setXDU@evalue@author@mprof@degree{}和学校模板对应不上

### ISSUE THREAD

**Issue by ZhanLiao** [note286/xdupgthesis#19]
关于LaTeX模板中个人信息有一处和学校给的模板对应不上。在xdupgthesis.cfg文件中：
\setXDU@evalue@author@mprof@degree{Electronics and Communications Engineering}{}
% 专业学位硕士研究生
% 专业硕士学位类别
% Finance
% Applied Statistics
% Translation
% Business Administration
% Public Administration
% Engineering
这里按照学校模板应该选择一级学科名字

**Comment by note286** [comment]
请阅读[增加专业学位硕士学位论文封面与中英文题名页](https://github.com/note286/xdupgthesis#%E5%A2%9E%E5%8A%A0%E4%B8%93%E4%B8%9A%E5%AD%A6%E4%BD%8D%E7%A1%95%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E5%B0%81%E9%9D%A2%E4%B8%8E%E4%B8%AD%E8%8B%B1%E6%96%87%E9%A2%98%E5%90%8D%E9%A1%B5)这一节，下载其中的压缩包，找到里面的`2、西安电子科技大学专业学位硕士学位论文封面及中英文题名页模板（2015年版）-2019.03修订.docx`文件，在第5页可以找到下拉菜单，里面就这几项，不是一级学科。你提到：

> 这里按照学校模板应该选择一级学科名字

这里的学校模板是指哪一个？

**Comment by ZhanLiao** [comment]
模板一样：`西安电子科技大学专业学位硕士学位论文封面及中英文题名页模板（2015年版）-2019.03修订.docx`
![image](https://user-images.githubusercontent.com/51037238/148049384-fc905e7b-6310-45a5-8efb-54ae642b4e15.png)
但是这里下拉菜单选的是一级学科

**Comment by note286** [comment]
我下载到的文件`2、西安电子科技大学专业学位硕士学位论文封面及中英文题名页模板（2015年版）-2019.03修订.docx`的MD5值为`A48A74E388BD8950CA58C23E1121DF45`
![QQ截图20220104190432](https://user-images.githubusercontent.com/16207292/148050002-f118aad1-841e-483f-b957-bea6dedbf4fd.jpg)

**Comment by note286** [comment]
@ZhanLiao 请问是否解答了你的疑惑？

**Comment by ZhanLiao** [comment]
我发现了，原来是我搞错了，我截图这个是学硕封面模板，你截图那个是专硕封面模板。

**Comment by note286** [comment]
好的，没问题就好。
