### ISSUE TITLE
目录里面没有目录

### ISSUE THREAD

**Issue by wanglj1997** [note286/xdupgthesis#20]
目录里面在绪论上面和缩略语对照表下面应该有目录。

**Comment by note286** [comment]
没懂你的意思，请具体描述。

**Comment by wanglj1997** [comment]
就是目录那的结构，我不会上传图片，直接用文字描述：
摘要	I
ABSTRACT	III
插图索引	V
表格索引	VII
符号对照表	IX
缩略语对照表	XI
目录	XIII
第一章	绪论	1
正常的目录应该是这样，但是现在编译出来的结果没有目录，也就是变成了这样：
摘要	I
ABSTRACT	III
插图索引	V
表格索引	VII
符号对照表	IX
缩略语对照表	XI
第一章	绪论	1

**Comment by note286** [comment]
就是没有目录的，你看学校的Microsoft Word模板，也没有目录，下面是Microsoft Word模板的截图。
![QQ截图20220105125859](https://user-images.githubusercontent.com/16207292/148162866-2eaffae3-3524-47dd-ae9e-a7f421571ca7.jpg)

**Comment by note286** [comment]
点击这里可以插入图片，然后点击Preview可以预览效果。
![QQ截图20220105130006](https://user-images.githubusercontent.com/16207292/148163053-80321b6f-e223-46eb-a159-d6f53e449fb1.jpg)

**Comment by wanglj1997** [comment]
谢谢，要是我想有个目录应该怎么改呀

**Comment by note286** [comment]
我有能力添加，但是我不会添加，因为你写的是学位论文，要符合学校的要求，这种格式问题不能凭自己的喜好来。
