### ISSUE TITLE
一个小问题，在引用图片的caption中使用\cite{}导致插图索引目录中同样出现引用是要求的吗

### ISSUE THREAD

**Issue by LLwyct** [note286/xdupgthesis#21]
引用图片的caption中使用\cite{}导致插图索引目录中同样出现\cite{}
```
\begin{figure}[htb]
    \centering
    \includegraphics[width=0.7\linewidth]{fig1-1}
    \caption{外部图片\cite{xxx}}
    \label{fig1-1}
\end{figure}
```

目录前的插图索引中同样出现引用
```
图1.1 外部图片^[1]
```
这会导致最终参考列表的顺序与正文中引用文章的顺序不一致，**因为"插图索引"要在正文之前**。我觉得**参考文献的顺序是与正文中引用的顺序一致更加合理。**

**Comment by note286** [comment]
估计不好实现，我考虑下吧。

**Comment by note286** [comment]
请阅读[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)。
