### ISSUE TITLE
修改目录

### ISSUE THREAD

**Issue by xfeng853** [note286/xdupgthesis#22]
这个目录要怎么修改啊，我要替换我自己的东西，比如第一章 是 绪论 
 ![1641544276(1)](https://user-images.githubusercontent.com/46802091/148515521-003188a5-4212-4f59-bede-2b7523307857.png)

**Comment by note286** [comment]
目录是自动生成的，你只需要写内容就好了，会自动根据你的`chapers`文件夹里的内容更新，无需手动处理。

**Comment by xfeng853** [comment]
好的，感谢，我先试一试

**Comment by note286** [comment]
看样子你可能没接触过LaTeX，你可以看一下[注意事项](https://github.com/note286/xdupgthesis#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)，我在里面有提到一个文档，可以了解一下LaTeX的基础知识。

**Comment by xfeng853** [comment]
好的好的，谢谢
