### ISSUE TITLE
无法显示数学符号

### ISSUE THREAD

**Issue by wanglj1997** [note286/xdupgthesis#24]
![2](https://user-images.githubusercontent.com/97144976/148686202-bae93ea8-e367-4fcd-bed9-8741281a0ba5.jpg)
![3](https://user-images.githubusercontent.com/97144976/148686206-b8a72ecc-3ced-4a81-b02c-6e5b9e4bdced.jpg)
![4](https://user-images.githubusercontent.com/97144976/148686207-0009f76a-7b57-4aba-a9d4-910b08bfc9fa.jpg)
用的编译器是texstudio，图一是编译出来的结果，图二是我在.tex文件写的，图三对应的是这个应该正确编译的结果。

**Comment by note286** [comment]
请具体描述问题。

**Comment by note286** [comment]
给出示例代码，用代码块环境。

**Comment by note286** [comment]
加粗是`\bm{}`。

**Comment by note286** [comment]
@wanglj1997 下次直接回复就可以，你编辑旧的内容我是没有提醒的，我要不是自己看，我都不知道你编辑了。
