### ISSUE TITLE
latexmk编译问题

### ISSUE THREAD

**Issue by wanglj1997** [note286/xdupgthesis#25]
按照给的方法修改了参数，但是还是出现下面问题。
![2](https://user-images.githubusercontent.com/97144976/148687567-c9b3417c-9ed6-47ae-b8f6-20cac292a1cd.jpg)
![3](https://user-images.githubusercontent.com/97144976/148687573-6d6abfc8-5ba3-4566-b306-035954597ddd.jpg)
![1](https://user-images.githubusercontent.com/97144976/148687578-737a036c-b6de-4531-b782-f19757d04df1.jpg)
xelatex编译没问题，环境是win10+texstudio4.1
![4](https://user-images.githubusercontent.com/97144976/148687625-e731ab61-089f-4018-b7bd-5c0dc72de10b.jpg)

**Comment by note286** [comment]
先用cmd执行
```shell
latexmk -c
latexmk
```
确认是否能够编译成功。

**Comment by wanglj1997** [comment]
还有出现这个图占了半页，看了那个浮动选项，调的是参数【h】
![5](https://user-images.githubusercontent.com/97144976/148687804-9d1562b7-0ec5-4184-be68-eb6d00d9dc24.jpg)
这个该怎么解决呢

**Comment by note286** [comment]
我才注意到你用的不是TeX Live，MiKTeX请自行搜索如何安装latexmk。

**Comment by note286** [comment]
图的问题请单开issue。
