### ISSUE TITLE
图直接占了一页的三分之二

### ISSUE THREAD

**Issue by wanglj1997** [note286/xdupgthesis#26]
![5](https://user-images.githubusercontent.com/97144976/148688498-85457b43-0fc6-4023-acc6-abbfd5ddb89e.jpg)
我看了那个浮动设置，参数设置为[h]

**Comment by note286** [comment]
建议阅读[浮动体位置](https://github.com/note286/xdupgthesis#%E6%B5%AE%E5%8A%A8%E4%BD%93%E4%BD%8D%E7%BD%AE)最后部分，仅根据你目前给出的素材，我无法做出更多的判断。

**Comment by wanglj1997** [comment]
![6](https://user-images.githubusercontent.com/97144976/148688710-f7746da1-c5e6-4eb5-9ef6-664801e39d7e.jpg)
这是我的tex文件部分

**Comment by note286** [comment]
建议阅读[浮动体位置](https://github.com/note286/xdupgthesis#%E6%B5%AE%E5%8A%A8%E4%BD%93%E4%BD%8D%E7%BD%AE)最后部分，设置一下那两个参数，是否可以调节。

**Comment by note286** [comment]
或者阅读[断页机制切换开关](https://github.com/note286/xdupgthesis#%E6%96%AD%E9%A1%B5%E6%9C%BA%E5%88%B6%E5%88%87%E6%8D%A2%E5%BC%80%E5%85%B3)，检查是否是所述问题。

**Comment by wanglj1997** [comment]
感谢，改了段页机制，现在正常了
