### ISSUE TITLE
引用参考文献显示[?]

### ISSUE THREAD

**Issue by sunsLorenzo** [note286/xdupgthesis#27]
在overleaf 和linux texlve TeX 3.14159265 (TeX Live 2019/Debian) 本地 编译后引用文献均显示[?] 没有正常显示序号

**Comment by note286** [comment]
Overleaf中选择XeLaTeX即可。参考README中关于命令编译的部分，使用`latexmk`编译即可。

**Comment by sunsLorenzo** [comment]
> Overleaf中选择XeLaTeX即可。参考README中关于命令编译的部分，使用`latexmk`编译即可。

命令行是可以的，但是texstudio和overleaf不行。是要配置那个texstudio和overleaf默认执行的命令吗

**Comment by note286** [comment]
请认真阅读README。
- TeXstudio请按照README进行配置。
- Overleaf的话测试过很多次，不会有问题的，你可以重新下载最新版模板，然后上传Overleaf，并按照README里进行配置。

**Comment by sunsLorenzo** [comment]
落了一个配置。。多谢了

**Comment by note286** [comment]
@sunsLorenzo star都不肯给一个嘛~~~///(^v^)\\\~~~
