### ISSUE TITLE
在overleaf上编译超时

### ISSUE THREAD

**Issue by david-spc** [note286/xdupgthesis#28]
你好，我下载模板后，根据说明上传至overleaf，并配置完成进行编译，但是编译显示显示超时，请问是什么原因

**Comment by note286** [comment]
请认真仔细地阅读[Overleaf编译](https://github.com/note286/xdupgthesis#overleaf%E7%BC%96%E8%AF%91)并按照要求操作，我刚刚按照文档测试了一下，没有任何问题。

**Comment by david-spc** [comment]
> 请认真仔细地阅读[Overleaf编译](https://github.com/note286/xdupgthesis#overleaf%E7%BC%96%E8%AF%91)并按照要求操作，我刚刚按照文档测试了一下，没有任何问题。

你好，我又重新设置了一下字体，这回可以了，可能是之前字体搞错了，感谢
