### ISSUE TITLE
关于硕士论文字号问题

### ISSUE THREAD

**Issue by Duanmu0312** [note286/xdupgthesis#29]
作者你好，非常感谢你修改后的Latex硕士毕业论文模板，但是我发现打印出来论文的字号和前面师兄们的毕业论文的字号好像小一点，想问一下关于字号的问题，当前模板的字号是正确的吗？

**Comment by note286** [comment]
正文都是小四字号，不放心可以查看`.cls`文件83行和111行，其中已指定`zihao=-4`。另外，你可以使用福昕PDF编辑器或者其他PDF编辑工具打开PDF，选择编辑对象功能，选择正文的某句话，查看对应的字号。

**Comment by Duanmu0312** [comment]
> 正文都是小四字号，不放心可以查看`.cls`文件83行和111行，其中已指定`zihao=-4`。另外，你可以使用福昕PDF编辑器或者其他PDF编辑工具打开PDF，选择编辑对象功能，选择正文的某句话，查看对应的字号。

好的谢谢，那也就是我们直接用编译器（比如TeXstudio）使用就行, 字体等格式问题，与编辑器配置无关对吧？（编码按你的文档配置）

**Comment by note286** [comment]
我都配置好了，但是不排除有遗漏，如果有任何觉得异常的地方，欢迎提issue。

**Comment by Duanmu0312** [comment]
> 我都配置好了，但是不排除有遗漏，如果有任何觉得异常的地方，欢迎提issue。

好的谢谢
