### ISSUE TITLE
缩略语对照表显示有点乱，这个格式间距我能自己调整么？

### ISSUE THREAD

**Issue by auroua** [note286/xdupgthesis#3]
缩略语对照表显示有点乱，如图所示，这个格式间距我能自己调整么？还有一个问题，如果一行写不下，我怎么控制换行?
![138030270-08a2b74e-28ad-47f2-89bd-21fa849ccf7c](https://user-images.githubusercontent.com/2869412/138038112-633de730-f35e-4df3-b1a8-625f8bdb41cc.png)

**Comment by note286** [comment]
@auroua https://github.com/note286/xdupgthesis/commit/3ad743e716f822879e0e19674daf3e58363679f8 已修复，请测试。
