### ISSUE TITLE
有关英文论文撰写时的问题

### ISSUE THREAD

**Issue by Negrain** [note286/xdupgthesis#30]
撰写英文论文时，其中章节序号，算法序号，插图序号，证明，页眉等等均为中文。另外，在正文中的参考文献引用时，文献引用偏上，没有与正文平齐(要求不在右上角活左上角)。

**Comment by note286** [comment]
请更新模板，并阅读README中相关内容。其中，关于参考文献引用序号位置，已咨询研究生院学位办，回复表示英文学位论文也在右上角。如果对于英文学位论文的支持仍然有问题，在该issue下留言即可。
