### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by YuanRuimin** [note286/xdupgthesis#31]
环境是TeXstudio2020，在编译时遇到以下问题
![problems](https://user-images.githubusercontent.com/34548166/150137473-f82012ae-83c8-4d1a-b3aa-c6b79b8b04de.PNG)

**Comment by note286** [comment]
TeX Live还是MiKTeX

**Comment by note286** [comment]
TeXstudio哪有2020这个版本？

**Comment by note286** [comment]
TeXstudio的版本号都是TeXstudio 4.1.1这种的。

**Comment by note286** [comment]
你是不是说的TeX Live 2020，建议更新到2021，README有写如何更新，更新到TeX Live 2021后再更新所有包。

**Comment by YuanRuimin** [comment]
感谢你的解答。
如果升级版本需要重新安装。为了简单，我下载了update-tlmgr-latest程序，然后执行了README里面给出的更新指令，但问题仍然存在。
后来我使用了LuaLaTex指令编译，就可以了。使用Latex、Xelatex都会有错。

**Comment by note286** [comment]
根据[tlmgr - TeX Live - TeX Users Group](https://www.tug.org/texlive/tlmgr.html)中的描述，`update-tlmgr-latest`只是用来避免Perl出现问题，无法运行tlmgr时使用，如果你使用TeX Live 2020，你是无法更新所有包至最新版的，因为旧版本的TeX Live的包已全部归档。之所以让你更新TeX Live 2021并更新所有包，是因为会出现[参考文献格式问题 · Issue #13 · note286/xdupgthesis](https://github.com/note286/xdupgthesis/issues/13)中所描述的问题。

**Comment by note286** [comment]
刚刚在Overleaf上的TeX Live 2020测试过，可以编译通过，如果使用XeLaTeX在TeX Live 2020上无法编译通过，请检查自己的环境配置。

![微信截图_20220120103203](https://user-images.githubusercontent.com/16207292/150261754-4960a75c-0935-48fa-80fa-e783af321625.png)

**Comment by note286** [comment]
另外，不知道你为啥LuaLaTeX可以编译成功，我是Windows平台的TeX Live 2021，无法编译通过。

![微信截图_20220120104022](https://user-images.githubusercontent.com/16207292/150262580-01f399a1-8b6c-4e96-a972-f334368ead6c.png)

**Comment by YuanRuimin** [comment]
问题已经解决！

可能是因为我之前装过CTEX的缘故，现在我把指令重定义到Tex Live2020下的exe程序，就可以了。

再次感谢您的耐心解答！
