### ISSUE TITLE
正文和图片超过页脚

### ISSUE THREAD

**Issue by wanglj1997** [note286/xdupgthesis#32]
![1](https://user-images.githubusercontent.com/97144976/150496579-66ac6a47-7a26-4766-bb62-8a80696a184e.jpg)
图片无法显示且论文正文都超过了页脚。
![Uploading 2.jpg…]()
这是这一部分的LaTeX文件部分。

**Comment by note286** [comment]
请重新编辑你的问题。

**Comment by wanglj1997** [comment]
![1](https://user-images.githubusercontent.com/97144976/150497839-42a003dd-d216-463b-adda-6caea403c9f3.jpg)
![2](https://user-images.githubusercontent.com/97144976/150497863-fc7db518-2d72-4d4e-80b3-d32ef1ba9aca.jpg)
图片无法显示且论文正文都超过了页脚。第二张图是对应的LaTeX文件部分。

**Comment by note286** [comment]
仅根据这些我无法复现，请问是否更新为最新模板。

**Comment by wanglj1997** [comment]
已经更新为最新一版了，我换了几个编译平台，都是超过了页脚

**Comment by wanglj1997** [comment]
已经更新为最新一版了，我换了几个编译平台，都是超过了页脚

**Comment by note286** [comment]
邮件[发我](mailto:note286@foxmail.com)一下完整代码吧，我需要测试。

**Comment by wanglj1997** [comment]
我直接用这个发可以不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "note286/xdupgthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [note286/xdupgthesis] 正文和图片超过页脚 (Issue #32)





 
邮件发我一下完整代码吧，我需要测试。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by note286** [comment]
哎，愁死了，直接点击上面的发我，这是个链接，或者右键查看链接也可以。

**Comment by wanglj1997** [comment]
已发送




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "note286/xdupgthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [note286/xdupgthesis] 正文和图片超过页脚 (Issue #32)





 
哎，愁死了，直接点击上面的发我，这是个链接，或者右键查看链接也可以。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by note286** [comment]
没有收到，你是不是发错了。

**Comment by note286** [comment]
你留下你的邮箱，我联系你。

**Comment by wanglj1997** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "note286/xdupgthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [note286/xdupgthesis] 正文和图片超过页脚 (Issue #32)





 
你留下你的邮箱，我联系你。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanglj1997** [comment]
1575504963@qq.com

**Comment by david-spc** [comment]
> 仅根据这些我无法复现，请问是否更新为最新模板。

我也遇到过问题，在overleaf上编译的时候

**Comment by note286** [comment]
目前已确定是`ltablex`宏包引起的问题，该宏包用来实现符号表和缩略语表的自动跨页功能。目前建议无需自动换行的表格不要使用`tabularx`环境，使用`tabular`环境即可。

**Comment by note286** [comment]
@david-spc 你在出现问题的页面附近是否也使用了`tabularx`环境。

**Comment by david-spc** [comment]
> @david-spc 你在出现问题的页面附近是否也使用了`tabularx`环境。

用到了，在附录中的表格示例中提供的是tabularx的样例，所以估计这个问题可能别人也会遇到，所以建议在readme中进行一下说明

**Comment by note286** [comment]
我尝试使用其他宏包完成符号表和缩略语表的自动跨页功能，避免该问题。

**Comment by note286** [comment]
@david-spc @wanglj1997 请更新最新版，已修复，注意阅读README中符号对照表和缩略语对照表的相关内容。

**Comment by david-spc** [comment]
> 符号对照表

好的谢谢，那正文中用到了tabularx的地方，是否需要修改，还是说按照现状即可

**Comment by note286** [comment]
@david-spc 保持现状即可，修复的目的就是确保`tabularx`可用。

**Comment by david-spc** [comment]
> @david-spc 保持现状即可，修复的目的就是确保`tabularx`可用。

 好的
