### ISSUE TITLE
list of figures字体重叠

### ISSUE THREAD

**Issue by bixiaopeng0** [note286/xdupgthesis#33]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/31760851/153322119-247970fd-35af-4ca5-be86-557994a2fe47.png">

如图所示，请问这个问题怎么解决呀？

**Comment by note286** [comment]
请阅读[插图/表格索引中图表序号与图表标题间距](https://github.com/note286/xdupgthesis#%E6%8F%92%E5%9B%BE%E8%A1%A8%E6%A0%BC%E7%B4%A2%E5%BC%95%E4%B8%AD%E5%9B%BE%E8%A1%A8%E5%BA%8F%E5%8F%B7%E4%B8%8E%E5%9B%BE%E8%A1%A8%E6%A0%87%E9%A2%98%E9%97%B4%E8%B7%9D)。
