### ISSUE TITLE
正文两侧间距不一致

### ISSUE THREAD

**Issue by bixiaopeng0** [note286/xdupgthesis#34]
<img width="138" alt="image" src="https://user-images.githubusercontent.com/31760851/153714801-65066de9-5aa0-45d7-9e33-c77275270c0c.png">

如图所示，正文两侧留出的空白间隙不一致，请问这个问题怎么解决？

**Comment by note286** [comment]
左右页边距本来就不同，为了装订。

**Comment by bixiaopeng0** [comment]
感谢回复
