### ISSUE TITLE
是否可以支持参考文献的平齐引用

### ISSUE THREAD

**Issue by FPGA-Networking** [note286/xdupgthesis#35]
- 西电学位论文有个要求，就是“文献”二字后面跟的引用，应该是平齐模式，而不是右上角，请问这该怎么实现？

**Comment by note286** [comment]
请问你说的这个要求文件在哪里，我问的学位办科长，回复是全部都是右上角。

**Comment by FPGA-Networking** [comment]
感谢您的回复，是上一届的博士师兄告诉我的； 我觉得应该以您的观点为准，谢谢！
|
|
|
|
|
在2022年2月15日 ***@***.***> 写道：

请问你说的这个要求文件在哪里，我问的学位办科长，回复是全部都是右上角。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by note286** [comment]
等正式上班之后我再和学位办沟通一下，你定稿前可以查看下README是否有更新。

**Comment by FPGA-Networking** [comment]
好的，谢谢。


| |
刘欢
|
|
***@***.***
|
在2022年2月15日 ***@***.***> 写道：

等正式上班之后我再和学位办沟通一下，你定稿前可以查看下README是否有更新。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by note286** [comment]
请阅读[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)。

**Comment by FPGA-Networking** [comment]
谢谢，请问学位办是有“文献二字之后使用正文引用”这个说法吗？

**Comment by note286** [comment]
目前没有正式规定说可以。已和学位办沟通，可以适当的时候使用正文模式，但是尽量减少使用。

**Comment by FPGA-Networking** [comment]
明白了，谢谢！

**Comment by note286** [comment]
在我有限的了解中，使用“文献[1]XXX”这种描述不是很规范，应该避免使用这种描述方式。

**Comment by FPGA-Networking** [comment]
嗯嗯，我也和师弟师妹们说一下这个问题，感谢您对此问题投入的精力！

**Comment by note286** [comment]
我的理解是引用的标号是可以移除，不影响正文的，这才叫参考文献引用，参考文献不应该参与正文，也可能我的理解不正确，如果你找到相关写作规范对此有描述，可以告知我，我会和学位办进行沟通。

**Comment by FPGA-Networking** [comment]
嗯嗯，好的。
