### ISSUE TITLE
定理类环境序号问题

### ISSUE THREAD

**Issue by ZhiyuanDang** [note286/xdupgthesis#36]
![image](https://user-images.githubusercontent.com/17498125/154182183-d6794d5b-926f-4a09-93d1-75efb55dd1e1.png)

请问序号1.1后面这个点可以去掉吗？感觉不太好看，其他定理环境也是这样。

**Comment by note286** [comment]
使用`\newtheoremstyle`定义新的样式，再使用`\theoremstyle`应用新样式即可，LaTeX默认使用的是内置的`plain`样式。举个简单的示例：

```latex
\newtheoremstyle{nodot}{}{}{}{}{}{}{}{}
\theoremstyle{nodot}
```

这是一个没有任何样式的定理样式，将其放在`\newtheorem`之前即可，如需更合适的，可以通过运行`texdoc amsthm`查看相关命令的使用。

**Comment by ZhiyuanDang** [comment]
好的，我改成 \newtheoremstyle{nodot}{}{}{}{}{\bfseries}{}{ }{}，现在有加粗了，感谢

**Comment by ZhiyuanDang** [comment]
嗨，有个相似的问题，我在附录A里面重新添加了第2章的引理，所以希望这里的引理是2.1开始的，而不是A.1开始的，请问该如何改动？
![image](https://user-images.githubusercontent.com/17498125/159885080-574a85b0-c7ef-4092-a615-866075f6d40d.png)
此外，还有一个问题，附录里面的公式序号貌似是从1-1开始的，这个貌似不太合理，如何改成从A-1开始计数？
![image](https://user-images.githubusercontent.com/17498125/159885680-4035e17a-7d72-4b68-8a82-1718b2b1b21b.png)

**Comment by note286** [comment]
@ZhiyuanDang 附录内公式编号问题已经修复，请更新。

**Comment by note286** [comment]
@ZhiyuanDang 你的第一个问题可以实现通过修改计数器来实现，但是不建议，如果是同一个定理，不应重复定义，直接引用即可。

**Comment by ZhiyuanDang** [comment]
请问计数器如何改动？我这里相当于重新写一遍，所以还是希望能改成2.1计数。\setcounter{lemma}{1}这样貌似不太对

**Comment by note286** [comment]
注意最外层的分组。
```latex
{\renewcommand{\thelemma}{2.1}
\begin{lemma}
XXX
\end{lemma}}
```
