### ISSUE TITLE
章节结尾生成了空白页

### ISSUE THREAD

**Issue by Nicooo-Wang** [note286/xdupgthesis#37]
你好同学，我想请问章节结尾生成了空白页时应该怎么做，是整页的空白，我查看了你的文档里好像没有写，我的编译环境是overleaf
实在不好意思麻烦你，我调了好久都调不出来
![image](https://user-images.githubusercontent.com/70059290/154212040-43452c6e-3964-42eb-aaa0-33b8e18f9cb8.png)

以下是该章论文代码

**Comment by note286** [comment]
每一章一定以奇数页开始，偶数页结束。不然怎么保证你打印出来每一章第一页是在右手边。

**Comment by Nicooo-Wang** [comment]
好的好的，谢谢，我还以为我的代码有问题，谢谢大佬拉
