### ISSUE TITLE
插图列表序号与标题重叠

### ISSUE THREAD

**Issue by wherelse** [note286/xdupgthesis#38]
![image.png](https://s2.loli.net/2022/02/17/Yiyh96UosqZxK43.png)
- 发现到序号大于10之后，插图列表序号与标题重叠
- 而且与word模板对照，图片索引和表格索引的序号与名称之间应该是有间隔的，不是紧跟的
![image.png](https://s2.loli.net/2022/02/17/8PFSCmnOpVYJuyH.png)

**Comment by note286** [comment]
请阅读[插图/表格索引中图表序号与图表标题间距](https://github.com/note286/xdupgthesis#%E6%8F%92%E5%9B%BE%E8%A1%A8%E6%A0%BC%E7%B4%A2%E5%BC%95%E4%B8%AD%E5%9B%BE%E8%A1%A8%E5%BA%8F%E5%8F%B7%E4%B8%8E%E5%9B%BE%E8%A1%A8%E6%A0%87%E9%A2%98%E9%97%B4%E8%B7%9D)。

我在 #33 里也回复过，麻烦认真读一下README，我写那么多不是闲得慌，就是为了让你们读的。

**Comment by wherelse** [comment]
抱歉，确实readme看的不够仔细，没看到这一条
