### ISSUE TITLE
公式和下一正文段落之间空白间隙过大

### ISSUE THREAD

**Issue by bixiaopeng0** [note286/xdupgthesis#39]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/31760851/154833445-12a94765-d561-483b-8285-545e75039e2f.png">
如图所示，请问这个问题怎么解决呀

**Comment by note286** [comment]
你看看是不是README里描述的断页机制切换开关的问题。

**Comment by bixiaopeng0** [comment]
对的，感谢
