### ISSUE TITLE
符号对照表格式问题

### ISSUE THREAD

**Issue by auroua** [note286/xdupgthesis#4]
符号对照表存在以下两个问题：
1、如图所示，太长了不能正确的显示
![138029560-52dcac5e-0435-4604-a3d1-4e6e1ae01fff](https://user-images.githubusercontent.com/2869412/138038227-d6c8f53c-a696-4e7a-b15a-b54439ff9457.png)

 2、符号对照表如果超过一页，他不自动到下一页，如图所示所示：
![138029550-069a1ba3-92d0-4cc6-b079-4e2ed49a21ee](https://user-images.githubusercontent.com/2869412/138038252-4c19caed-504b-4160-8e90-17622cf671cf.png)

**Comment by note286** [comment]
@auroua https://github.com/note286/xdupgthesis/commit/c3f70839d19addd8dc69d23e6e9cba7ae7c59227 已修复问题1，问题2正在修复中。

**Comment by note286** [comment]
@auroua https://github.com/note286/xdupgthesis/commit/92bdddf347eaac16b6fe463afc528e5203f3aec7 问题2已修复，请测试。

**Comment by auroua** [comment]
谢谢,已经修改好了
