### ISSUE TITLE
关于参考文献没有出版商出现[S.1.:s.n.]问题

### ISSUE THREAD

**Issue by Duanmu0312** [note286/xdupgthesis#40]
你好，学位论文参考文献bib没有出版商，但在参考文献中出现了[S.1.:s.n.]。这个问题上网查了一下，说是什么版本格式问题，在我的电脑上没有出现，但是同门的电脑上出现了这个。我们两个的latex版本和使用的编译器及版本都是一样的。

**Comment by note286** [comment]
看README，更新所有包至最新版即可解决。

**Comment by Duanmu0312** [comment]
好的 谢谢 我试试

**Comment by note286** [comment]
确认问题解决之后麻烦close该issue。

**Comment by Duanmu0312** [comment]
好的

**Comment by Duanmu0312** [comment]
你好，他下载了最新的版本，还是有上述问题~

**Comment by note286** [comment]
安装TeX Live 2021，然后更新所有包。

**Comment by Duanmu0312** [comment]
好 我再让他试试 谢谢，解决的话 我把这个issue关了

**Comment by note286** [comment]
README里这些我都写的很清楚，尤其是你问的这个问题，我特意说了不更新会导致这个后果，读啊，同学们，愁死我了，怎么就不知道阅读文档呢。

**Comment by Duanmu0312** [comment]
嗯嗯好的，感谢大哥，之前会错意了 以为要更新最新的论文模板，应该是更新Tex。
