### ISSUE TITLE
图片标题不居中

### ISSUE THREAD

**Issue by DizzyKnight233** [note286/xdupgthesis#42]
使用minipage让两张图同行显示，图片标题换行就不居中
```
\begin{figure}[htbp]
    \begin{minipage}{0.45\linewidth}
    \centering
    \includegraphics[width=.9\linewidth]{S3/XXXX/XXX}
    \caption{XXXXXXXXXXXX\\询问信号XXXX图}
    \label{HXXXXask}
    \end{minipage}
    \hfill
    \begin{minipage}{0.45\linewidth}
    \centering
    \includegraphics[width=.9\linewidth]{S3/XXXX/XXXX}
    \caption{XXXXXXXXX\\询问信号XXXX图}
    \label{HXXXXXask}
    \end{minipage}
 \end{figure}
```
尝试使用中文换行```\texorpdfstring{\\}{}```依然不行，总共以这种方法放了8张图，大部分没问题，小部分第二行跟第一行对齐了，只有这一张两行都是左对齐
![微信截图_20220222112018](https://user-images.githubusercontent.com/19530766/155057094-24d52c59-584d-4068-b5b4-0708a80f1884.png)

**Comment by note286** [comment]
建议使用子图，模板内有示例。

**Comment by DizzyKnight233** [comment]
因为每张图都是不同信号的，需要单独编号，子图没找到有和其他图一起排号的方法所以才这么写的

**Comment by note286** [comment]
你为啥认为`\texorpdfstring{\\}{}`是中文换行。

**Comment by DizzyKnight233** [comment]
也不是说中文换行，就是.cfg里中文标题让用这个换行，我就说试一试

**Comment by DizzyKnight233** [comment]
老哥你瞅瞅，要是不好搞了我给他一行一个图也问题不大

**Comment by note286** [comment]
> 也不是说中文换行，就是.cfg里中文标题让用这个换行，我就说试一试

你理解错了，这是避免书签出现空白。

**Comment by note286** [comment]
以后遇到非模板问题记得自己Google搜索，[horizontal alignment - How to center a caption inside a minipage? - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/210729/how-to-center-a-caption-inside-a-minipage)。

另外在我看来，一行只应该有一个图啊，为啥要并排放，这不符合排版的规矩吧。

**Comment by DizzyKnight233** [comment]
我看之前的毕设有这么写的，刚问了一下应该就是一行一个，被误导了。谢谢大佬
虽然但是这个问题还是没解决...无论是把```\centering```放在```\includegraphics```之前还是之后还是都放还是都不放，这个标题它就是不居中

**Comment by note286** [comment]
我已经告诉你解决方法了啊，测试过没问题了啊，你没看吗？

**Comment by DizzyKnight233** [comment]
我这边还是不行，第一行超过一定字数就gg。具体的也忘了，已经改回一行一个图了

**Comment by note286** [comment]
我已经在你这浪费一定的时间了，你把你的完整的这部分代码发一下，我测试一下。

**Comment by DizzyKnight233** [comment]
去吃了个饭重启了电脑突然好了...像是什么tex的bug，没有变代码，就是上面的代码加了```\captionsetup{justification=centering}```，其他没啥变化

感谢楼主，我给关了

**Comment by DizzyKnight233** [comment]
我意思之前加了也不生效，然后啥都没改又好了

**Comment by note286** [comment]
行吧，后面多看看lshort和README，别乱抄代码，能避免很多问题。

**Comment by DizzyKnight233** [comment]
好的好的，学到了
