### ISSUE TITLE
算法格式变化

### ISSUE THREAD

**Issue by ZhiyuanDang** [note286/xdupgthesis#43]
V4.0的版本，出来的算法版本是这样的
![image](https://user-images.githubusercontent.com/17498125/155721454-766d0e9c-c808-4ec8-8fe8-9c580f83cf83.png)
而以前是这样的
![image](https://user-images.githubusercontent.com/17498125/155721487-4635a8e3-db1b-49a7-81f8-8e4afe4a2c81.png)

请问下我想用之前的格式怎么办？

**Comment by note286** [comment]
`.cls`里将`\RequirePackage{algpseudocodex}`替换为`\RequirePackage{algpseudocode}`。

另外，之前的并不利于阅读。

**Comment by ZhiyuanDang** [comment]
长算法的话，确实不利于阅读，但是短的话， 还是旧版的好看点。。

**Comment by note286** [comment]
下一个大版本我会移除所有非必须宏包，完全由用户自行添加，避免这种情况，不过要快年底发布了。
