### ISSUE TITLE
长表格的处理建议

### ISSUE THREAD

**Issue by ZhiyuanDang** [note286/xdupgthesis#44]
我有个表格列比较多，已经超出页面了，  不太美观，使用\tiny等调整字号无效。

请问我是调整字号好点还是直接用resizebox整个表格包裹整个表格？

**Comment by note286** [comment]
由于学校规定了字号是5号，我已经设置好了字号，建议你调整表格结构。

**Comment by ZhiyuanDang** [comment]
好的，麻烦了
