### ISSUE TITLE
table和figure转换问题

### ISSUE THREAD

**Issue by bixiaopeng0** [note286/xdupgthesis#46]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/31760851/155870221-d7e2e726-d4b2-4ad3-ba0d-3c11ad89a3d7.png">
如图所示，请问怎么把自动生成的figure和table变成中文的图和表呀？

**Comment by bixiaopeng0** [comment]
每张图会有一个标题，例如figure3.3 xxx，其中figure3.3是自动生产的。我想把figure3.3改成图3.3 ，请问应该怎么改啊

**Comment by note286** [comment]
比较好奇你用`babel`宏包来做什么？

**Comment by bixiaopeng0** [comment]
从之前会议论文顺手复制过来的

**Comment by note286** [comment]
除了研究外语的，咱学校应该很少有学生需要处理多国语。不用的宏包不要引入，很容易出现问题，这不是一个好习惯。
