### ISSUE TITLE
使用Algorithm2e报错问题

### ISSUE THREAD

**Issue by jpgong** [note286/xdupgthesis#47]
请问在该latex模板中如何兼容Algorithm2e包，我这边报错说冲突了。
![image](https://user-images.githubusercontent.com/27892657/156098951-a70ae32d-a4d7-4b2b-969c-6bc674a91973.png)

**Comment by note286** [comment]
已内置`algpseudocodex`宏包，阅读文档[algpseudocodex.pdf](https://mirrors.ustc.edu.cn/CTAN/macros/latex/contrib/algpseudocodex/algpseudocodex.pdf)查看使用方法和示例，不推荐使用`algorithm2e`宏包。

**Comment by jpgong** [comment]
好的，我也找到了algorithm2e的一个解决方法，https://tex.stackexchange.com/questions/131646/algorithm2e-command-algorithm-already-defined。
谢谢
