### ISSUE TITLE
请问页眉下双横线的宽度如何更改

### ISSUE THREAD

**Issue by wbchao1997** [note286/xdupgthesis#48]
目前宽度较宽，难以看出是双横线
![image](https://user-images.githubusercontent.com/48538713/156486126-0d7adb1a-b40b-4801-92f5-dad288252f7d.png)

**Comment by wbchao1997** [comment]
PDF同等缩放尺度下正常的是这样
![image](https://user-images.githubusercontent.com/48538713/156486381-fd0df3d0-d46f-4549-ba7f-9c10dc9827a8.png)

**Comment by note286** [comment]
PDF阅读器的问题，你打印一页看一下，是正常的。

**Comment by wbchao1997** [comment]
好的

**Comment by wbchao1997** [comment]
> PDF阅读器的问题，你打印一页看一下，是正常的。

打印出来双横线是挨在一起的，这个可以调吗

**Comment by wbchao1997** [comment]
已修改cls文件调整成功
