### ISSUE TITLE
图中字体和字号问题

### ISSUE THREAD

**Issue by Hanqer** [note286/xdupgthesis#49]
请问如何确保图中字号与caption中的字体和字号保持一直? 在作图时进行设置 然后不改变图片大小，还是使用overpic 调整字号字体?

**Comment by note286** [comment]
在LaTeX插入图片时不改变图片尺寸，作图时设置好字号即可。

**Comment by Hanqer** [comment]
使用overpic的\small标识是否满足比正文字体小一号的五号字体呢？

**Comment by note286** [comment]
为什么不在制图软件里绘制好呢？你这样操作还需要对齐，不是很麻烦。

**Comment by Hanqer** [comment]
ok 好的3q   个人感觉overpic在latex里编辑比较方便

**Comment by note286** [comment]
能具体说一下使用场景吗？比较好奇。

**Comment by note286** [comment]
> 使用overpic的\small标识是否满足比正文字体小一号的五号字体呢？

可以。

**Comment by Hanqer** [comment]
好的，主要是使用overpic可以不打开绘图软件直接修改一些图中的文字、公式等，可以直接在latex里修改比较方便。

**Comment by note286** [comment]
你是指类Microsoft Visio绘图还是类MATLAB绘图？

**Comment by Hanqer** [comment]
Visio的绘图

**Comment by note286** [comment]
Microsoft Visio的话，可以添加快捷打印按钮，一键生成pdf文件，配合`pdfcrop`自动裁边，即使在Microsoft Visio内部修改，也是非常方便的。

**Comment by Hanqer** [comment]
好的 谢谢
