### ISSUE TITLE
如图xxxx显示不正确，多了一个图字

### ISSUE THREAD

**Issue by auroua** [note286/xdupgthesis#5]
如一下latex内容，和对应的pdf中显示的内容所示，显示的多了一个图字

`latex`的内容
![微信截图_20211020151605](https://user-images.githubusercontent.com/2869412/138045925-5b7a4e91-fe5d-4bb4-93b6-cf6e7d3bdd41.png)

显示的内容
![微信截图_20211020151617](https://user-images.githubusercontent.com/2869412/138045951-816b7d3d-6277-43f5-9059-bae89d9b4402.png)

**Comment by auroua** [comment]
@note286 已经正确显示了，谢谢大佬，大佬辛苦了。

**Comment by note286** [comment]
@auroua 之前对索引表上的前缀实现方式逻辑不是很合理才导致的问题。不过我发现，其实索引表上的每一项的前缀没有必要存在，图片索引里的一定是图，没必要说`图 2.1`，直接说`2.1`即可。后期看大家如果反馈吧，现在的实现逻辑很清晰，后期如果有需要可以提供一个开关前缀的参数，这样大家视情况自行开启或者关闭都是可以的。
