### ISSUE TITLE
希腊字母加粗

### ISSUE THREAD

**Issue by wbchao1997** [note286/xdupgthesis#50]
\mathbf{\Gamma}加粗希腊字母后显示为方格
![image](https://user-images.githubusercontent.com/48538713/156523630-697ce706-7b0c-4b1d-a5f3-185d2799a52a.png)
之前的版本是正常的
![image](https://user-images.githubusercontent.com/48538713/156523777-47a9d299-c71f-4256-8d28-5f38099e643e.png)
使用\bm会变成斜体
![image](https://user-images.githubusercontent.com/48538713/156523952-f0a647d5-aeb3-4491-8bec-8d4dfb5b501e.png)

**Comment by note286** [comment]
阅读[unicode-math.pdf](https://mirrors.ustc.edu.cn/CTAN/macros/unicodetex/latex/unicode-math/unicode-math.pdf)第6页。
