### ISSUE TITLE
自动生成的插图索引在图标号超过1位的时候会出现问题

### ISSUE THREAD

**Issue by xsliu2018** [note286/xdupgthesis#52]
硬件环境mbp，软件环境overleaf
![示例1](https://user-images.githubusercontent.com/39669753/156994828-3bbf20da-4a4f-4422-bed7-1cceb0c89258.png)
![示例2](https://user-images.githubusercontent.com/39669753/156994978-64398199-5b69-40ab-a6fe-2c6b3f21ed54.png)

**Comment by note286** [comment]
阅读README。

**Comment by Christine620** [comment]
你好，我也有这个问题

**Comment by ZhanLiao** [comment]
你好最后问题怎么结局的，我看readme,要把两行代码加到导言区？请问导言区是哪个文件

**Comment by ZhanLiao** [comment]
已解决，感谢
