### ISSUE TITLE
参考文献水平引用有问题

### ISSUE THREAD

**Issue by 15901821251** [note286/xdupgthesis#53]
请问使用\citen{}命令得到的文献序号前面有空格该怎么解决呢？（使用\citenum{}也是这样的结果）
![微信截图_20220308163343](https://user-images.githubusercontent.com/45559223/157198416-0f75ea8f-2727-4463-848a-9fab3837b4df.png)

**Comment by note286** [comment]
测试没问题。

**Comment by note286** [comment]
另外并没有提供`\citenum{}`命令，你哪里看到的。

**Comment by 15901821251** [comment]
谢谢，已解决。（\citenum{}是网页上搜到的）

**Comment by note286** [comment]
已解决？之前咋出的问题？

**Comment by 15901821251** [comment]
重新下载了一次模板就好了
