### ISSUE TITLE
参考文献Bug

### ISSUE THREAD

**Issue by DeepLearning723** [note286/xdupgthesis#54]
原始tex文件中貌似没有涉及到参考文献如何添加进去，直接用XeLaTex编译参考文献显示不出来。我参考之前写过的英文论文加了如下代码：
![image](https://user-images.githubusercontent.com/52575426/157427300-28a41d06-c487-4cf9-840d-3a16829812ff.png)

**Comment by note286** [comment]
不需要用户配置参考文献文件，默认处理。
