### ISSUE TITLE
论文psd模式（相似性检测模式）下online条目的引用报错不可用

### ISSUE THREAD

**Issue by jaysshao** [note286/xdupgthesis#55]
论文psd模式（相似性检测模式）下online条目的引用报错不可用，显示undefined
而用普通默认的模式，可以通过，引用正常

**Comment by note286** [comment]
给出相应的bib条目，便于测试。

**Comment by jaysshao** [comment]
即使用原生bib条目：
@online{Collinson21,
author = {Stephen Collinson},
title = {Biden's refusal of executive privilege claim ignites new firestorm with {Trump}},
url = {https://edition.cnn.com/2021/10/26/politics/donald-trump-joe-biden-executive-privilege-january-6/index.html},
urldate = {2021-10-26}
}
报错信息如下：
<img width="398" alt="image" src="https://user-images.githubusercontent.com/28103733/158049355-372bcc41-5275-4135-ad81-abb2c577607a.png">
在正文中就是一个问号[?]

**Comment by note286** [comment]
我这边没有任何问题，请你从GitHub下载最新的模板，并将`\include{chapters/reference}`移动至附录环境外，再使用`latexmk`编译查看结果。

**Comment by jaysshao** [comment]
问题依旧，可能是我mac配的环境问题，打算切换到win上试试，谢谢作者的回复

**Comment by note286** [comment]
是否使用MacTeX2021，并更新所有包至最新版，试一试。

**Comment by jaysshao** [comment]
确定是MacTeX2021，更新了所有包后，问题解决，感谢！
