### ISSUE TITLE
个人简介不能自动换行

### ISSUE THREAD

**Issue by Who-Am-I25** [note286/xdupgthesis#56]
请问作者简介中发表学术论文部分不能自动换行该怎么解决？如果不手动\\，就会超出边框范围。

**Comment by note286** [comment]
请给出测试用例，模板内置的用例是没问题的。

**Comment by Who-Am-I25** [comment]
![1](https://user-images.githubusercontent.com/45559223/158124221-511e99a5-37df-41c4-8e69-266d815ef80c.png)

**Comment by note286** [comment]
你这样我也没法测试，你可以尝试把论文名称用其他单词替换，能复现你的问题即可。

**Comment by Who-Am-I25** [comment]
\resumelistitem \anonrvwinfo{author}{学生第一作者}.abcaaaaaaaaaaa aaaaaaaa aaaa aaaaaaaaaa aa Haaaaaaaaaeous aaaaaa aaae Caaautaaa Naaaoaaa[J]. IEEE Taaaaaaaions on Aaaacuaaa Raaaaaaoaa.

![1](https://user-images.githubusercontent.com/45559223/158125978-6b679fa0-e83c-4cca-a6df-4880bc5c2c71.png)

**Comment by note286** [comment]
`abcaaaaaaaaaaa`前添加空格即可。

**Comment by note286** [comment]
可以使用[CTAN: Package seqsplit](https://ctan.org/pkg/seqsplit?lang=en)宏包来解决。
