### ISSUE TITLE
关于数学公式前后空行问题

### ISSUE THREAD

**Issue by Duanmu0312** [note286/xdupgthesis#57]
![99d8d6d3b8603828a431ce4909960e0](https://user-images.githubusercontent.com/57739052/158292642-b9e9aa5f-a410-4959-ab14-c14c1ccbacb0.png)
![fb0fe3fc120af0e02babdaf8972a281](https://user-images.githubusercontent.com/57739052/158292648-009f9d12-d45b-4c98-a410-2b409d0aeecb.png)

你好，帮朋友问，上图为latex代码和公式效果，这似乎并没有前后空行，想问一下怎么前后空行，读readme没发现有解决方法。

**Comment by note286** [comment]
由于这些公式都是高度大于普通文本一行的公式，你将公式替换成简单的行高为普通文本高度的即可看出效果，目前这部分是由LaTeX自动处理的，本模板未进行特殊的处理，暂未找到合适的方法解决。

**Comment by note286** [comment]
另外，麻烦将图2中对应的源代码使用代码环境贴出来，我测试一下。这是语法，[Basic writing and formatting syntax - GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)。

**Comment by Duanmu0312** [comment]
```
\begin{normalsize}
\begin{equation}
 {V_{BE}} = {V_T}\ln \left( {\frac{{{I_C}}}{{{I_S}}}} \right)
\end{equation}
\end{normalsize}

现将（4-7）中$I_{S}$对温度T求偏导，可得到求导结果如（4-9）所示：

\begin{normalsize}
\begin{equation}
 \frac{{\partial {I_S}}}{{\partial T}} = b(4 + m){T^{3 + m}}{e^{\frac{{ - {E_g}}}{{kT}}}} + b{T^{4 + m}}{e^{\frac{{ - {E_g}}}{{kT}}}}\frac{{{E_g}}}{{k{T^2}}}
\end{equation}
\end{normalsize}

由（4-8）式可知，$V_{BE}$成负温度系数，将$V_{BE}$对T求偏导可得式（4-10）。

\begin{normalsize}
\begin{equation}
 \frac{{\partial {V_{BE}}}}{{\partial T}} = \frac{{\partial {V_T}}}{{\partial T}}\ln \frac{{{I_C}}}{{{I_S}}} - \frac{{{V_T}}}{{{I_S}}}\frac{{\partial {I_S}}}{{\partial T}}
\end{equation}
\end{normalsize}

所以有：

\begin{normalsize}
\begin{equation}
 \frac{{{V_T}}}{{{I_S}}}\frac{{\partial {I_S}}}{{\partial T}} = (4 + m)\frac{{{V_T}}}{T} + \frac{{{E_g}}}{{k{T^2}}}{V_T}
\end{equation}
\end{normalsize}

将公式（4-10）与（4-11）联立可以得到：

\begin{normalsize}
\begin{equation}
 \frac{{\partial {V_{BE}}}}{{\partial T}} = \frac{{{V_{BE}} - (4 + m){V_T} - {E_g}/q}}{T}
\end{equation}
\end{normalsize}

式（4-12）给出了在温度T下$V_{BE}$的温度系数，可以看出，他与工艺参数和$V_{BE}$本身带下也有关系，当$T=300K$，$V_{BE}=750mV$时，此时公式（4-12）为：

\begin{normalsize}
\begin{equation}
 \frac{{\partial {V_{BE}}}}{{\partial T}} \approx  - 1.5mV/K
\end{equation}
\end{normalsize}
```

**Comment by note286** [comment]
首先，哪里学的使用`normalsize`环境？其次，公式和上一段文本不要有空行，这样会产生换段。修改后你再看下效果。

**Comment by Duanmu0312** [comment]
好的 我试一下 谢谢

**Comment by Duanmu0312** [comment]
![微信图片_20220315160213](https://user-images.githubusercontent.com/57739052/158332541-50a483a2-324f-4521-ae28-fd8c833aefbe.png)
似乎还是不行

**Comment by Hanqer** [comment]
@note286 同样的问题，采用equation或align环境，公式上下距离并不能保持一行正文大小的空行，请问有什么解决方案吗？ 只能通过\vspace手动调整吗？ 谢谢

**Comment by Hanqer** [comment]
@note286 可以通过该方法解决，但两个equation连续出现时，需要在后面的equation内手动添加\setlength{\abovedisplayshortskip}{-10pt}才能达到预期效果。

**Comment by note286** [comment]
@Hanqer 你试试在`\begin{document}`之后添加
```latex
\setlength{\abovedisplayskip}{20pt plus 10pt minus 10pt}
\setlength{\abovedisplayshortskip}{20pt plus 10pt minus 10pt}
\setlength{\belowdisplayskip}{20pt plus 10pt minus 10pt}
\setlength{\belowdisplayshortskip}{20pt plus 10pt minus 10pt}
```

**Comment by Hanqer** [comment]
@note286  似乎与直接设置{20pt}没有区别

**Comment by note286** [comment]
@Hanqer @Duanmu0312 以下是LaTeX默认的参数配置：

```latex
\setlength{\abovedisplayskip}{12.0pt plus 3.0pt minus 7.0pt}
\setlength{\abovedisplayshortskip}{0.0pt plus 3.0pt}
\setlength{\belowdisplayskip}{12.0pt plus 3.0pt minus 7.0pt}
\setlength{\belowdisplayshortskip}{6.5pt plus 3.5pt minus 3.0pt}
```

以下是我调配出的参数：

```latex
\setlength{\abovedisplayskip}{20pt plus 5pt minus 11.5pt}
\setlength{\abovedisplayshortskip}{0pt plus 5pt}
\setlength{\belowdisplayskip}{20pt plus 5pt minus 11.5pt}
\setlength{\belowdisplayshortskip}{10.5pt plus 6pt minus 5pt}
```

如果不满意，可以根据默认值自行调节，将这部分代码放置在`\begin{document}`下方即可。

**Comment by Duanmu0312** [comment]
非常感谢你的调整，按照你最后所给出的代码，可以解决一部分问题，但是好像有个bug，，请参考公式（4-5），下图1是对的，下图2是不对的。问题在于公式上面的文字的多少，文字如果在公式正上方（铺满超半行），就是正常的。如果文字不在公式正上方（如该行两三个字），那就不正常。
![2](https://user-images.githubusercontent.com/57739052/158504617-51641318-d55b-4f50-8dd6-bd8e2c72ab34.png)
![1](https://user-images.githubusercontent.com/57739052/158504608-092e46b4-ea89-44ad-bb5f-67beec2bf9c1.png)

**Comment by Hanqer** [comment]
@Duanmu0312  Latex根据公式和上下方文字的长短自动在equation中嵌入displayskip 或 displayshortskip，感觉可以根据自己的需要去调整了。

**Comment by note286** [comment]
@Hanqer @Duanmu0312 这是合理的，如果前面的文字行在公式开始之前就结束，即公式和前面的文字没有重叠部分时，使用`\abovedisplayshortskip`，否则使用`\abovedisplayskip`。

**Comment by note286** [comment]
我最近在撰写response letter，暂无时间进行细致的调整，如果你们有调整好的参数，可以回复下，后续我会考虑添加至模板中。

**Comment by Hanqer** [comment]
请问 @note286 ， 后面的plus和minus是用来调整什么的呢？ 在overleaf的说明中没有找到对应解释 [overleaf abovedisplayskip](https://www.overleaf.com/learn/latex/%5Cabovedisplayskip_and_related_commands)

**Comment by Duanmu0312** [comment]
@Hanqer 感觉当前调整是按公式的中间线来调整的，你知道怎么按照公式的上下边缘调整吗？如果按中间线调整，正常公式和带分式的公式空行间距不相等。 如（4-1）和（4-2）的上边缘
![1](https://user-images.githubusercontent.com/57739052/158506650-e1f2571e-0b08-4144-a16d-22d33710952a.png)

**Comment by note286** [comment]
@Duanmu0312 目前我也不知道，你使用空模板，即干净的`book`文档类，也依然如此，感觉是LaTeX内核就这样。

**Comment by Duanmu0312** [comment]
@note286 好的 那就先目前这样吧，感觉也还可以。后面的plus和minus是用来调整什么的呢？

**Comment by Hanqer** [comment]
@Duanmu0312 也不是按照中心，而是有一个边界，但是这个边界由于分式和矩阵等导致的并不一样。  最丑的解决方案是在global环境中嵌入这个调整，然后自己在每个需要进一步调整的公式里面嵌入这个命令进一步细微调整。

**Comment by note286** [comment]
@Hanqer 阅读lshort第5.3.1章节。

**Comment by note286** [comment]
@Duanmu0312 阅读lshort第5.3.1章节。

**Comment by Duanmu0312** [comment]
好的 谢谢 @note286 @Hanqer

**Comment by Hanqer** [comment]
已查阅，多谢

**Comment by note286** [comment]
学位办很多规定都是以美观为目的，并不是很严格，由于当时制定规定的人员并不是一线写作的人。例如虽然要求所有的文献引用必须右上角，但是和学位办沟通后，部分情况下是可以使用正文模式的引用样式。

个人觉得默认的其实就挺好，空一行真的不是很美观，后续我会和学位办进一步沟通。

**Comment by note286** [comment]
@Hanqer @Duanmu0312 估计你们应该用不上了。

昨天我测试了一下，搞懂了这四个参数的作用。

`\abovedisplayskip`、`\belowdisplayskip`、`\abovedisplayshortskip`和`\belowdisplayshortskip`均仅检测公式上方文字内容的长短，不检测下方文字，哪怕是`\belowdisplayskip`和`\belowdisplayshortskip`也是如此。也就是说，只要公式上方文字与公式垂直方向有重叠部分，就使用`\abovedisplayskip`和`\belowdisplayskip`，如果没有重叠部分就使用`\abovedisplayshortskip`和`\belowdisplayshortskip`。

连续多个公式的间距，第一个公式与正文的间距符合上面的解释，对于公式之间的间距，例如第一个公式和第二个公式的间距，我没有找到文档对此有解释，实测后我给的解释是，从第二个公式起，认为处于与上面正文垂直方向无重叠的情况，因此，从第二个公式起，一律使用`\abovedisplayshortskip`和`\belowdisplayshortskip`。

因此，对于学校要求的公式与正文空一行，同时兼顾美观，我给出的参数设置为：

```latex
\ExplSyntaxOn
\dim_set:Nn \abovedisplayskip      { 12bp }
\dim_set:Nn \belowdisplayskip      { 12bp }
\dim_set:Nn \abovedisplayshortskip { 0bp  }
\dim_set:Nn \belowdisplayshortskip { 12bp }
\ExplSyntaxOff
```

该功能已在 https://github.com/note286/xduts/commit/e5184d0495f29625dc5b34dbf6616dd40a9e0b18 中解决。
