### ISSUE TITLE
PSD模式下的页眉删除问题

### ISSUE THREAD

**Issue by Hanqer** [note286/xdupgthesis#59]
请问psd 论文相似性检测模式下的删除内容中的 页眉  并非研究生院规定的删除内容，是否应该要删除呢？ 
此外，在学期间的研究成果需要去除，是否要去除作者基本信息呢？

**Comment by note286** [comment]
> 提交检测的学位论文电子版必须为论文的正文部分（除去封面、目录、参考文献、附录、致谢、在学期间的研究成果等）

注意这个`等`字，再领悟一下`正文部分`四个字。

**Comment by Hanqer** [comment]
正文精神已领悟，多谢。
