### ISSUE TITLE
论文抽查评估

### ISSUE THREAD

**Issue by UraniumZll** [note286/xdupgthesis#60]
请问能否增加论文盲审的格式要求，去除创新性声明、附录、致谢等，其它与抽审类似，谢谢！

**Comment by note286** [comment]
请给出官方规定链接。

**Comment by UraniumZll** [comment]
https://ste.xidian.edu.cn/info/1337/6254.htm  感谢

**Comment by note286** [comment]
非常抱歉，最近暂无时间处理，论文回复审稿意见的最后期限快到了，你先使用`anonrvw`参数后，再使用学校购买的福昕阅读器自行移除页面吧。

**Comment by UraniumZll** [comment]
好的 谢谢，祝论文投稿顺利！
