### ISSUE TITLE
网页参考文献引用[?]

### ISSUE THREAD

**Issue by share-xh** [note286/xdupgthesis#63]
作者您好，请问引用网页的参考文献，在相似相检测（[psd]）的模板中，运行出来是[?]，，但是正常版本就是对的，请问 这怎么解决？。运行结果提示警告：chapters\general.tex:5: Package natbib Warning: Citation `GWY19' on page 1 undefined on input line 5.
`GWY19'是参考的网页文献，模式如下。
@online{GREENBERG15,
	author = {ALISSA GREENBERG},
	title = {Google Lost Data After Lightning Hit Its Data Center in Belgium},
	url   = {https://time.com/4004192/google-data-lightning-belgium/},
	urldate  = {2015-8-20}
}
@online{GWY19,
	author = {国务院发展研究中心国际技术经济研究所},
	title = {中国云计算产业发展与应用白皮书},
	url   = {http://www.soft6.com/news/201910/13/358570.html},
	urldate  = {2019-10-12}
}
并且在全文总结之后会加一页出现  网页参考文献的几个索引。

**Comment by note286** [comment]
已测试你的两个文献引用没有任何问题。

请按照如下操作进行测试，下载一份空模板，添加这两个文献后，再在正文(非附录)中引用这两个文献，再添加`psd`参数，直接使用latexmk编译，最后查看结果。

**Comment by share-xh** [comment]
谢谢解答，我刚下载了您的最新4.2.0模板,我用的sublime用xelatex编译进行了测试，仍然还是[?]。
请问必须使用latexmk才可以吗？

**Comment by note286** [comment]
必须要交叉引用才可以啊。

**Comment by note286** [comment]
直接cmd里输入`latexmk`执行即可。

**Comment by share-xh** [comment]
谢谢您的解答，我刚使用cmd运行latexmk结果仍然是[?]， 我用的是texlive2020，请问您使用的是2021运行[psd]吗？

**Comment by note286** [comment]
TeX Live 2021且更新所有包至最新版，README开头已经明确说了不是TeX Live 2021且不更新所有包至最新版的后果，请认真阅读。

**Comment by share-xh** [comment]
嗯嗯  好的，谢谢您的解答，我更新之后再试一下。

**Comment by note286** [comment]
请认真阅读README，上面没有废话，不要浪费我的成果。
