### ISSUE TITLE
关 键 词 这三个字之间需要有空格

### ISSUE THREAD

**Issue by KORIYN** [note286/xdupgthesis#65]

**Comment by note286** [comment]
并无硬性规定，不需要完全比对Microsoft Word模板。

**Comment by note286** [comment]
@KORIYN 为避免你担心，已咨询学位办，不需要空格。另外多说一句，除了个别强制规定外，大部分要求的目的只有一个，美观，而且不要过度迷信Microsoft Word模板，模板开发时也有疏忽的。
