### ISSUE TITLE
符号对照表格式

### ISSUE THREAD

**Issue by DizzyKnight233** [note286/xdupgthesis#66]
如果用lp默认7cm而符号又很短，就无法居中，如图
![微信截图_20220319112736](https://user-images.githubusercontent.com/19530766/159104964-024e069a-2497-448d-a313-c8c38aa0dfca.png)
于是我只能将符号名称列设的很长，但是这样挤在一起又很难看
```
\begin{symbollist}{lp{13cm}}
```
![image](https://user-images.githubusercontent.com/19530766/159105027-6bef04e2-d5fc-473c-9cc4-4ba1ba5bfd20.png)

看了下word模板和往届论文都是这样
![image](https://user-images.githubusercontent.com/19530766/159105012-f2d812fa-eb28-4437-a339-f328faf79cac.png)

**Comment by note286** [comment]
去lshort了解一下l和p都是啥意思。

**Comment by DizzyKnight233** [comment]
l是左对齐，p是列宽，但是用```{cp{7cm}}```名称列也没有居中，还是下面的样子，就是不知道该怎么设置符号列参数
![image](https://user-images.githubusercontent.com/19530766/159105546-99324cd5-7281-4e08-b13b-eb675801d7c5.png)

**Comment by note286** [comment]
为什么不两列都用p。

**Comment by note286** [comment]
这就是一个普通的列表语法，不在模板的范畴内，请学好基础知识。

**Comment by DizzyKnight233** [comment]
奥奥这就懂了，表格这块大概也明白，理解错readme里的意思了，一直以为这两个参数都是设置右列的
