### ISSUE TITLE
subfloat的caption字号问题

### ISSUE THREAD

**Issue by Hanqer** [note286/xdupgthesis#67]
你好，观察到目前模板中的subfloat caption字体大小 与figure caption大小不一致，请问如何修改至规定的五号字体大小？

**Comment by Hanqer** [comment]
请问为何close了issue？ 有可行的解决方案吗

**Comment by note286** [comment]
这是更新自动关闭的，已经解决了啊，你没看见你问题下面那一行吗？

**Comment by Hanqer** [comment]
看到了，谢谢
