### ISSUE TITLE
符号对照表和缩略语对照表行高问题

### ISSUE THREAD

**Issue by wherelse** [note286/xdupgthesis#69]
![Snipaste_2022-03-27_21-41-03.jpg](https://s2.loli.net/2022/03/27/nAbQ4TIcSyUE7LD.jpg)  
学校学位论文模板要求中，符号对照表和缩略语对照表要求行距为20磅  
![Snipaste_2022-03-27_21-51-18.jpg](https://s2.loli.net/2022/03/27/O4N52YzkuDW6Qpo.jpg)  

上图中左侧为latex模板，pdf 100%大小下截图，图中右侧为word模板，导出pdf，100%大小下的截图，将两者截图后，不改变大小的情况下对比行距，latex行距较word模板较大。
![Snipaste_2022-03-27_21-58-27.jpg](https://s2.loli.net/2022/03/27/Ze7H5OSEMyKa1vf.jpg)
上图为latex模板的符号对照表截图和latex模板中正文内容截图，对比行距，符号对照表行距比正文行距大

我查看模板设置中，两个对照表的设置为`\renewcommand{\arraystretch}{1.6666666667}`，对应小四字高12磅，1.6666666667倍的字高为20磅，但是显示效果确实不一致。

**Comment by note286** [comment]
学位办的核心精神就是美观即可，实际无严格要求。

**Comment by wherelse** [comment]
> 学位办的核心精神就是美观即可，实际无严格要求。

那这种差异，似乎是表格本身的特性带来的吗？对这个原因也比较好奇

**Comment by note286** [comment]
小四为12bp，72.27pt=72bp。

**Comment by wherelse** [comment]
更新后的间距似乎仍然不一致，我实际打印测试，\renewcommand{\arraystretch}设置到约为1.33左右，间距和word模板的20磅间距接近

**Comment by wherelse** [comment]
> 更新后的间距似乎仍然不一致，我实际打印测试，\renewcommand{\arraystretch}设置到约为1.33左右，间距和word模板的20磅间距接近

反复测试后，\renewcommand{\arraystretch}设置到1.375，打印测试以及pdf对比的效果和word模板基本完全一致

**Comment by note286** [comment]
@wherelse 同学你好，你的问题已经在 https://github.com/note286/xduts/commit/f6337d3311779ebc04536a7730345a3249ce6085 里解决了，虽然你可能用不上了:joy:。
