### ISSUE TITLE
section行间隔不正常

### ISSUE THREAD

**Issue by Nicooo-Wang** [note286/xdupgthesis#7]
![image](https://user-images.githubusercontent.com/70059290/141807185-a3f1065d-4822-4c38-a91e-dd3c0d1f949f.png)
大佬先看上边这张照片，第八章的截图是你的文件生成的pdf（使用overleaf），感觉行间距正常，但是我的第二章明显正文部分没有对齐
两个章节的代码是一模一样的，贴图部分是你的代码，代码框里是我的代码，可以看到都是capter+section+正文的结构，但为什么排版出来的pdf行间距结构却不一样
![image](https://user-images.githubusercontent.com/70059290/141807639-23f8b826-1b60-46c8-b1ea-f1946ff4f735.png)

**Comment by note286** [comment]
@Nicooo-Wang `正文部分没有对齐`是指什么？我没有发现有哪里不对劲？请详细指出。如果你指的是`（1）行间距：固定值 20 磅（题名页除外）。`与`（2）字符间距：标准。`的间距与你的行间距不同，那你仔细看一下源代码，这里的示例，每个都是一段，`\par`是分段的意思，等价于空一行，所以间距更大，`（4）页码设置：`这一段是多行的，这个才是一般意义上的行间距。

**Comment by Nicooo-Wang** [comment]
我的意思是，同样都是chapter+section+正文的格式，为什么我的正文和他的正文高度不同，在章节那里是完全对齐着的
![image](https://user-images.githubusercontent.com/70059290/141886467-8196dcc8-d422-4ebd-8939-3f4b75e6217b.png)

**Comment by note286** [comment]
> 我的意思是，同样都是chapter+section+正文的格式，为什么我的正文和他的正文高度不同，在章节那里是完全对齐着的 ![image](https://user-images.githubusercontent.com/70059290/141886467-8196dcc8-d422-4ebd-8939-3f4b75e6217b.png)

根据我浅薄的观察，是因为你的pdf缩放比例不同。你的章节对齐了，但是页眉的线没有对齐，说明你的pdf缩放比例不同。

**Comment by Nicooo-Wang** [comment]
> > 我的意思是，同样都是chapter+section+正文的格式，为什么我的正文和他的正文高度不同，在章节那里是完全对齐着的 ![image](https://user-images.githubusercontent.com/70059290/141886467-8196dcc8-d422-4ebd-8939-3f4b75e6217b.png)
> 
> 根据我浅薄的观察，是因为你的pdf缩放比例不同。你的章节对齐了，但是页眉的线没有对齐，说明你的pdf缩放比例不同。

并不是缩放比例的不同，先看这张图
![image](https://user-images.githubusercontent.com/70059290/141887077-7c56ff67-f248-4118-825e-7ec4d11f91d7.png)
拖动到水平位置后，发现明显不在同一条水平线上
![image](https://user-images.githubusercontent.com/70059290/141887260-11e9b1da-8faf-4535-ae18-b2b9c2caeeb0.png)

**Comment by note286** [comment]
> > > 我的意思是，同样都是chapter+section+正文的格式，为什么我的正文和他的正文高度不同，在章节那里是完全对齐着的 ![image](https://user-images.githubusercontent.com/70059290/141886467-8196dcc8-d422-4ebd-8939-3f4b75e6217b.png)
> > 
> > 
> > 根据我浅薄的观察，是因为你的pdf缩放比例不同。你的章节对齐了，但是页眉的线没有对齐，说明你的pdf缩放比例不同。
> 
> 并不是缩放比例的不同，先看这张图 ![image](https://user-images.githubusercontent.com/70059290/141887077-7c56ff67-f248-4118-825e-7ec4d11f91d7.png) 拖动到水平位置后，发现明显不在同一条水平线上 ![image](https://user-images.githubusercontent.com/70059290/141887260-11e9b1da-8faf-4535-ae18-b2b9c2caeeb0.png)

![20211116105655](https://user-images.githubusercontent.com/16207292/141887722-fa40a790-dfab-431c-af8f-3c565d45cf95.png)

两种方法：第一种，你先调整pdf缩放，使得两条蓝色线所指位置位于同一水平线，这两个算是基准点，基准点都对不齐，怎么对比其他的，接着你就会发现一致了，你两个pdf的缩放依然没有一致，所以才会这样。第二种，你将这两页pdf单独提取出来，合并成一个pdf，然后用本地pdf阅读器打开，使用双页模式浏览，这样两页pdf缩放一定一致。

**Comment by note286** [comment]
@Nicooo-Wang 你把左半部分的开头部分代码贴到代码块里给我，我测试下，我需要复现，才能找原因。

**Comment by Nicooo-Wang** [comment]
> @Nicooo-Wang 你把左半部分的开头部分代码贴到代码块里给我，我测试下，我需要复现，才能找原因。

看了下代码块好像不支持latex的插入，是我插入方法的问题吗。。
第二章代码如下：
`\chapter{不完全约束索牵引二轴摇摆系统的静态逆运动学解}
\section{引言}
根据Ming和Higuchi对关于对索牵引系统的分类，\cite{MING1994}，设$m$为牵引绳索的数量，$n$为可控自由度数量，索牵引系统可分为以下几种。
（1）$m<n<6$：该类系统为不完全约束系统\textit{incompletely restrained positioning mechanism}(\textbf{IRPM})。通常情况下末端执行器产生任意的力旋量，当系统运行在重力条件下，会像钟摆一样会具有一组稳态位姿。同时由于其为欠约束，部分自由度是不可控的。
（2）$n=m$：系统为运动学完全约束，当其运行在重力条件下，可以通过收紧或放松绳索使末端执行器产生力旋量，从而使其运动或对环境施加外力。但由于该类系统同样需要运行在重力条件下，因此也属于不完全约束系统\textbf{IRPM}
（3）$n+1=m$：该类系统为完全约束系统\textit{completely restrained positioning mechanisms}(\textbf{CRPM})，末端执行器所能产生的力旋量取决于绳索拉力的上下限，通过合理配置绳索的出索点与入索点，系统可以在多个自由度上旋转或平移。
（4）$n+1<m$：该类系统为冗余约束系统\textit{redundantly restrained positioning mechanisms}(\textbf{RRPM})，其显著特点为驱动副的数量大于自由度，索力通常有多组解，由于驱动副的数量更多，产生的运动也可以相对复杂。


对于\textbf{CRPM}以及\textbf{RRPM}的运动学，已经有很多学者做过研究\cite{Gao2014, Merlet2018, Pott2010}，然而对于\textbf{IRPM}的运动学与\textbf{CRPM}和\textbf{RRPM}不同，其显著差异在于对于\textbf{IRPM}，当驱动器完全锁定，即索长不变时，末端执行器仍可以自由移动，最终在重力或外力条件下静止于唯一的能量最低点。因此，求解其静态逆运动学解相对于\textbf{CRPM}和\textbf{RRPM}更加复杂，需要同时满足索力方程及索长方程，即几何静力问题\cite{Carricato2013b,Carricato2010}(\textit{geometrico-static problems})
\section{不完全约束索牵引二轴摇摆系统的逆运动学分析}
我校研究生学位论文包括以下几个部分：


\section{不完全约束索牵引二轴摇摆系统的逆运动学分析}


\section{不完全约束索牵引二轴摇摆系统的逆运动学分析}`

你的第八章代码如下：
`\chapter{研究生学位论文的编辑、打印、装订要求}
\section{学位论文封面的编辑和打印要求}
学位论文的封面由研究生院按国家规定统一制定印刷，封面内容必须打印，不得手写。
\section{学位论文的版面设置要求}
（1）行间距：固定值20磅（题名页除外）。
\par
（2）字符间距：标准。
\par
（3）页眉设置：单面页码页眉标题为章节题目，每一章节的起始页必须在单面页码，双面页码页眉标题统一为“西安电子科技大学博/硕士学位论文”，页眉标题居中排列，字体为宋体，字号为五号。页眉文字下添加双横线，双横线宽度为0.5 磅，距正文距离为：上下各1磅，左右各4磅。
\par
（4）页码设置：学位论文的前置部分和主体部分分开设置页码，前置部分的页码用罗马数字标识，字体为Times New Roman，字号为小五号；主体部分的页码用阿拉伯数字标识，字体为宋体，字号为小五号。页码统一居于页面底端中部，不加任何修饰。
\par
（5）页面设置：为了便于装订，要求每页纸的四周留有足够的空白边缘，其中页边距为上3厘米、下2厘米；内侧2.5厘米、外侧2.5厘米；装订线为0.5厘米；页眉2厘米，页脚1.75厘米。
\section{学位论文的打印、装订要求}
（1）打印：学位论文必须用A4纸页面排版，双面打印；
\par
（2）装订：依次按照中文题名页、英文题名页、声明、摘要、插图索引、表格索引、符号对照表、缩略语对照表、目录、正文、附录（可选）、参考文献、致谢、作者简介的顺序，用学校统一印制的学位论文封面装订成册。盲审论文必须删除致谢部分的文字内容（致谢标题须保留）以及封面和研究成果中的作者和指导教师姓名，研究成果列表中应体现作者的排序，如第一作者、第一发明人等。
\section{其他说明}
本规定由研究生院负责解释，从申请2015年9月毕业和授位的研究生开始执行，其它有关规定同时废止。研究生毕业论文撰写要求参照学位论文撰写要求执行。`

麻烦老哥了，一大早上的！真的辛苦，谢谢！

**Comment by note286** [comment]
@Nicooo-Wang 
```latex
这是代码块
```

有空复习下语法[Creating and highlighting code blocks - GitHub Docs](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)，我先测试去。

**Comment by Nicooo-Wang** [comment]
> @Nicooo-Wang
> 
> ```
> 这是代码块
> ```
> 
> 有空复习下语法[Creating and highlighting code blocks - GitHub Docs](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)，我先测试去。

```
🙉🙉🙉我不想活啦
```

**Comment by note286** [comment]
@Nicooo-Wang 这个问题我想起来了，我上个月写模板的时候就发现了，我下午具体和你解释原因，我再提供一个文档类选项来让用户自行选择选择哪种排版方式。

**Comment by Nicooo-Wang** [comment]
> @Nicooo-Wang 这个问题我想起来了，我上个月写模板的时候就发现了，我下午具体和你解释原因，我再提供一个文档类选项来让用户自行选择选择哪种排版方式。

```
好的，谢谢大佬拉，辛苦辛苦
```

**Comment by note286** [comment]
@Nicooo-Wang 已增加切换功能，请阅读[断页机制切换开关](https://github.com/note286/xdupgthesis#%E6%96%AD%E9%A1%B5%E6%9C%BA%E5%88%B6%E5%88%87%E6%8D%A2%E5%BC%80%E5%85%B3)。
