### ISSUE TITLE
论文封面的作者姓名处填写论文编号问题

### ISSUE THREAD

**Issue by DangJC** [note286/xdupgthesis#78]
根据[电院送审论文要求](https://see.xidian.edu.cn/index.php/News/index/id/11293)：

> 论文封面的作者姓名处必须填写上论文编号，编号规则如下：
>
>  **论文编号**：2204+班级序号（191为1,192为2，以此类推）+个人学号后四位，**各信息段之间用下划线分隔**。例如191班学号1902120945的同学，论文编号为：**2204_1_0945**

模板给的解决办法是：用户可以在对应处填写论文抽查评估版本显示的内容，例如：

```latex
\setXDU@value@author@name{张三}{031}
```

添加文档类型参数`anonrvw`后，实际操作发现：

- 当使用连贯数字，如031，编译正常；
- 当数字中有下划线，如2204_1_0945，**编译报错**；

**Comment by note286** [comment]
`\_`，这是LaTeX基础知识，不是模板范畴。
