### ISSUE TITLE
提示TeX capacity exceeded, sorry [input stack size=5000].

### ISSUE THREAD

**Issue by Nicooo-Wang** [note286/xdupgthesis#8]
![image](https://user-images.githubusercontent.com/70059290/141814770-5ad2d127-d6ab-459a-ae4c-244b585f633b.png)
报错图片如上，定位到\cite{CarricatoGeometricoStaticAnalysis332010}出错，pdf能正常引用但是持续报错，该引用bib文件如下，请问该如何修复？（使用软件citavi）
![image](https://user-images.githubusercontent.com/70059290/141815167-d99292e4-f34d-4a6d-9f5a-ef0a70d59980.png)

**Comment by note286** [comment]
@Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。

**Comment by Nicooo-Wang** [comment]
> @Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。

你好谢谢，这个代码错误在doi部分下划线被\textunderscore替代了，昨晚联系了overleaf客服已经修复了，麻烦你啦

**Comment by note286** [comment]
> > @Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。
> 
> 你好谢谢，这个代码错误在doi部分下划线被\textunderscore替代了，昨晚联系了overleaf客服已经修复了，麻烦你啦

建议你读一下[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)，bib没必要写这么多项，尤其是DOI，GB/T 7714-2015会显示DOI，没必要。

另外，都有GitHub账号，给个star呗。

**Comment by Nicooo-Wang** [comment]
> > > @Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。
> > 
> > 
> > 你好谢谢，这个代码错误在doi部分下划线被\textunderscore替代了，昨晚联系了overleaf客服已经修复了，麻烦你啦
> 
> 建议你读一下[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)，bib没必要写这么多项，尤其是DOI，GB/T 7714-2015会显示DOI，没必要。
> 
> 另外，都有GitHub账号，给个star呗。

好的，star一定给嘿嘿，平常用GitHub不怎么多，就没这习惯，很感谢大佬，昨晚提交的issue今天一大早就来fix，真的是非常感动，做这个latex模板也花费大佬不少时间吧，十分感谢！bib是自动导出的，这怎么可能手写，疯了😂😂😂

**Comment by note286** [comment]
> > > > @Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。
> > > 
> > > 
> > > 你好谢谢，这个代码错误在doi部分下划线被\textunderscore替代了，昨晚联系了overleaf客服已经修复了，麻烦你啦
> > 
> > 
> > 建议你读一下[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)，bib没必要写这么多项，尤其是DOI，GB/T 7714-2015会显示DOI，没必要。
> > 另外，都有GitHub账号，给个star呗。
> 
> 好的，star一定给嘿嘿，平常用GitHub不怎么多，就没这习惯，很感谢大佬，昨晚提交的issue今天一大早就来fix，真的是非常感动，做这个latex模板也花费大佬不少时间吧，十分感谢！bib是自动导出的，这怎么可能手写，疯了😂😂😂

你把多余的项删除，我在模板bib文件里给出了常用的示例，你仅保留和我一致的项即可，其余删除就可以了，具体原因README里有写。

**Comment by Nicooo-Wang** [comment]
> > > > > @Nicooo-Wang 请把这段bib源代码贴到代码块环境中，方便我测试。
> > > > 
> > > > 
> > > > 你好谢谢，这个代码错误在doi部分下划线被\textunderscore替代了，昨晚联系了overleaf客服已经修复了，麻烦你啦
> > > 
> > > 
> > > 建议你读一下[参考文献引用](https://github.com/note286/xdupgthesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8)，bib没必要写这么多项，尤其是DOI，GB/T 7714-2015会显示DOI，没必要。
> > > 另外，都有GitHub账号，给个star呗。
> > 
> > 
> > 好的，star一定给嘿嘿，平常用GitHub不怎么多，就没这习惯，很感谢大佬，昨晚提交的issue今天一大早就来fix，真的是非常感动，做这个latex模板也花费大佬不少时间吧，十分感谢！bib是自动导出的，这怎么可能手写，疯了😂😂😂
> 
> 你把多余的项删除，我在模板bib文件里给出了常用的示例，你仅保留和我一致的项即可，其余删除就可以了，具体原因README里有写。

好的好的，多谢大佬，这个issue可以关闭啦，麻烦拉
