### ISSUE TITLE
伪代码里面使用\Comment命令实现注释

### ISSUE THREAD

**Issue by FPGA-Networking** [note286/xdupgthesis#81]
伪代码里面使用\Comment命令实现注释，结果会出现方框加问号，如图所示

![未命名1654785714](https://user-images.githubusercontent.com/56921202/172875625-ab1062fa-94e8-4f25-8737-5c99d99d0218.png)
![未命名1654785735](https://user-images.githubusercontent.com/56921202/172875641-10038151-1152-423c-a9f8-5c17ea29e8d5.png)

**Comment by note286** [comment]
这是我的测试结果，TeX Live 2022。目前看来是你的问题，你无法显示三角形符号，这个符号是使用相应的数学字体显示的，你换同学的电脑测试一下，这个与模板无关。

```latex
\begin{algorithm}[!h]
    \caption{算法示例.}
    \label{alg_hyperparser_ibf_bf_routing}
    \begin{algorithmic}[1]

    \Procedure{Function}{x}
        \State test \Comment{This is test code}
    \EndProcedure

    \end{algorithmic}
\end{algorithm}
```

![image](https://user-images.githubusercontent.com/16207292/172883707-36445fcd-34d2-46cb-8aa5-f0cc1dca3436.png)

**Comment by FPGA-Networking** [comment]
明白了，谢谢！
