### ISSUE TITLE
章标号变成附录，bib参考文献没有出现

### ISSUE THREAD

**Issue by RenShijie** [note286/xdupgthesis#82]
你好，请问为什么texstudio用xelatex模式编译之后，4、5、6章的标号全部变成附录A、B、C了呢？bib里面的参考文献也没有出现，可能需要改哪些地方呢？

**Comment by note286** [comment]
请阅读[附录](https://github.com/note286/xdupgthesis#%E9%99%84%E5%BD%95)相关文档。
