### ISSUE TITLE
算法伪代码中的注释\Comment{}

### ISSUE THREAD

**Issue by piaochong-design** [note286/xdupgthesis#83]
在算法伪代码中，正常使用\Comment{}后会生成注释，显示为一个倒三角。自己的目的是想将这个倒三角替换成// 或者 /* */。在参考文档algpseudocodex.pdf中的解决方案中，发现一直会报错，显示有冲突等。
![onea](https://user-images.githubusercontent.com/59725239/175610245-a45c8594-39f7-465e-be99-a0d2c40fd6b5.png)
![twoa](https://user-images.githubusercontent.com/59725239/175610261-8f97e2f8-a4e5-462d-860c-f0abf5b21bd8.png)

**Comment by shudong-zhang** [comment]
我也想换成"//"请问这个是怎么解决的？

**Comment by note286** [comment]
本项目不再维护，请使用[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)。

请阅读[algpseudocodex](http://mirrors.ctan.org/macros/latex/contrib/algpseudocodex/algpseudocodex.pdf)文档。
