### ISSUE TITLE
去年停止维护的原因是什么，今年还想再使用能否使用

### ISSUE THREAD

**Issue by hanhaoxuan163** [note286/xdupgthesis#84]
##### 请问去年停止维护的原因是什么，今年还想再使用能否再使用

**Comment by note286** [comment]
看README第一行。

**Comment by hanhaoxuan163** [comment]
那请问新的xduts中是不包含模板了吗，其中目前包含的xdupgthesis.cls文件又在哪呢



在 2022-11-12 15:18:55，"Chloe" ***@***.***> 写道：

看README第一行。

**Comment by note286** [comment]
请根据README获取PDF文档和文档类文件，再阅读PDF文档进行使用。
