### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by ymmz** [note286/xdupgthesis#85]
你好，我根据文档进行安装查看新的文档以后，发现全都是格式的说明，也就是说新的库里面没有模板需要自己根据文档写吗？
然后我简单修改了一下，发现还是回报未知命令的错误，也就是说新旧的隔离不太兼容，不能用旧模板吗？

**Comment by note286** [comment]
两个是独立的，推荐使用[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)，[note286/xdupgthesis: [停止维护]西安电子科技大学研究生学位论文XeLaTeX模板](https://github.com/note286/xdupgthesis)已经不再维护。

[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)中，阅读README获取文档类和PDF文档，阅读PDF文档使用即可。

**Comment by ymmz** [comment]
好的，感谢！
