### ISSUE TITLE
插图和插表目录问题

### ISSUE THREAD

**Issue by qwli111** [note286/xdupgthesis#86]
<img width="279" alt="1673243029525" src="https://user-images.githubusercontent.com/122252139/211247097-4053bb07-f741-46a3-94d5-4e3086d14570.png">
在插图和插表目录中，图号和标号与标题之间的距离太近，会导致编号与文字重叠，能否告知如何解决？

**Comment by note286** [comment]
建议使用[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)。

另外，你所述的问题README里有说明。

**Comment by qwli111** [comment]
十分抱歉打扰你的时间。我刚看到了，问题已解决。
