### ISSUE TITLE
请问停止维护的西电研究生毕业论文版本里面关于每章的标题字体在哪个文件里改？我的绪论字体没有加粗。

### ISSUE THREAD

**Issue by yzyzzzzz** [note286/xdupgthesis#88]
![1](https://github.com/note286/xdupgthesis/assets/90914433/94149d81-45cc-4f4a-9c34-faf068d627e5)

**Comment by note286** [comment]
请使用[note286/xduts: 西安电子科技大学LaTeX套装](https://github.com/note286/xduts)。当前项目已停止维护，如需帮助，请付费咨询。
