### ISSUE TITLE
参考文献具体格式

### ISSUE THREAD

**Issue by 602311329** [note286/xdupgthesis#89]
听说参考文献有很多细小的要求，想问一下在bib中，@article和@inproceedings的哪些属性是必须存在的呢？需要修改什么其他配置吗？
![QQ截图20240320194316](https://github.com/note286/xdupgthesis/assets/93909893/5d692cdb-0c31-40f7-878d-23bb261f4627)

**Comment by note286** [comment]
请参考 https://github.com/zepinglee/gbt7714-bibtex-style 。

**Comment by 602311329** [comment]
好的，感谢回复
