### ISSUE TITLE
两张图占了一整页

### ISSUE THREAD

**Issue by DizzyKnight233** [note286/xdupgthesis#9]
您好，没有加任何位置参数，两张图片占了整页，一算法一图片也出现过这个情况
<img width="176" alt="微信截图_20211117200542" src="https://user-images.githubusercontent.com/19530766/142197887-da1fb9f9-f668-4cff-93c3-6a4ca8614a7b.png">

**Comment by note286** [comment]
@DizzyKnight233 已经更新了模板，修改了默认参数，README中增加了[浮动体位置](https://github.com/note286/xdupgthesis#%E6%B5%AE%E5%8A%A8%E4%BD%93%E4%BD%8D%E7%BD%AE)说明。
